# פסיקת CEO — Gibraltar Industries (ROCK)
**תאריך: 2026-06-01 | סוכן: CEO**

---

## [0] אימות קלטים

| קלט | סטטוס |
|-----|-------|
| Analyst Handoff | ✅ מלא — ציון 6/10, פסיקת REVIEW |
| Devil's Advocate Handoff | ✅ מלא — ציון סיכון 7/10 |
| טבלת תיק | ✅ הודבקה — 11 פוזיציות, $1,986.22 |

**אישור: כל הקלטים נמצאים. מתחיל ניתוח.**

---

## [1] תמונת מצב תיק נוכחית

```
═══════════════════════════════════════════════════
  תמונת מצב תיק — נקרא מהנתונים שסופקו
  תאריך: 2026-06-01
═══════════════════════════════════════════════════

  סה"כ שווי תיק:    $1,986.22
  מספר פוזיציות:    11
  מזומן זמין:       $71.00 (3.6%)
═══════════════════════════════════════════════════
```

| שכבה | קיים % | יעד % | סטטוס | פעולה נדרשת |
|------|--------|-------|-------|-------------|
| Stability | 30.7% | 25–35% | 🟢 תקין | — |
| Growth | 49.3% | 55–65% | 🔴 נמוך מהיעד ב-5.7pp | הוספת Growth בעדיפות |
| Speculation | **16.3%** | 5–10% | 🔴🔴 גבוה פי 1.6 מהתקרה | **קיצוץ דחוף** |
| Cash | 3.6% | 5–10% | 🔴 מתחת למינימום | בניית מזומן נדרשת |

**פוזיציות מובילות:**
| # | פוזיציה | % תיק | שכבה | סטטוס |
|---|---------|-------|------|-------|
| 1 | NVDA | 13.3% | Growth | 🔴 מעל מקסימום שכבה (12%) |
| 2 | MSFT | 10.9% | Stability | 🟢 תקין |
| 3 | META | 10.5% | Growth | 🟢 תקין |
| 4 | IBIT | **10.0%** | Speculation | 🔴🔴 **פי 2.5 ממקסימום שכבה (4%)** |
| 5 | GLDM | 10.0% | Stability | 🟢 תקין |

**ריכוז לפי תמה:**
| תמה | % תיק | הערכה |
|-----|-------|-------|
| AI / Tech | 62.1% (NVDA+META+MSFT+GOOG+AVGO+MU) | 🔴 ריכוז גבוה — אסטרטגי |
| אנרגיה / חשמל | 14.5% (VST+OKLO+APLD) | 🟡 גבוה |
| ביטקוין / קריפטו | 10.0% (IBIT) | 🔴 מעל מקסימום ספקולציה |
| זהב / הגנתי | 10.0% (GLDM) | 🟢 תקין |
| רגיש לריבית | 28.9% (MSFT+GOOG+AVGO) | 🟡 לשים לב |

**נדרש איזון מחדש: כן — דחוף**
→ Speculation 16.3% חורגת משמעותית. IBIT לבדה (10%) פי 2.5 ממקסימום פוזיציה בשכבה.
→ NVDA (13.3%) עולה על מקסימום Growth (12%).
→ מזומן (3.6%) מתחת למינימום.

---

## [2] בדיקת התאמה לתיק

**שיוך שכבה:** ROCK שייכת ל**ספקולציה** — לא Growth.

הסיבה: המבנה הפיננסי של ROCK הוא בינארי לחלוטין. Leverage 3.9x על חברה עם $20M מזומן הופך אותה לאופציה ממונפת, לא לחברת Growth. כפי שהדגים עורך הדין השטן בחישוב הלברג': EBITDA miss של 31% = equity כמעט אפס. זה לא Growth — זה Speculation.

**האם השכבה פנויה?**

```
ספקולציה נוכחית: 16.3%
יעד שכבה: 5-10%
מקסימום פוזיציה: 4%

IBIT לבד: 10.0% (פי 2.5 מהמקסימום)
OKLO: 4.0% (בדיוק במקסימום)
APLD: 2.4% (מתחת למקסימום)

הוספת ROCK ב-2.5% → Speculation = 18.8% → עוד יותר גרוע.
```

🔴 **השכבה לא פנויה. שכבת הספקולציה נמצאת בחריגה משמעותית גם ללא ROCK.**

**ניתוח חפיפה (Overlap):**

| פוזיציה קיימת | חפיפה עם ROCK | הערכה |
|--------------|--------------|-------|
| NVDA, META, GOOG, MSFT, AVGO, MU | אפס — ROCK בנייה, לא AI/Tech | 🟢 דיברסיפיקציה מצוינת |
| IBIT | אפס | 🟢 |
| GLDM | אפס | 🟢 |
| VST, OKLO, APLD | חפיפה חלקית — ROCK מחזורי כמו VST (GDP-sensitive) | 🟡 קלה |
| MSFT, GOOG | שניהם רגישי ריבית; ROCK רגיש ריבית בשני ממדים (ביקוש דיור + עלות חוב) | 🟡 סיכון מאקרו משותף |

**מסקנת חפיפה:** ROCK מוסיפה דיברסיפיקציה תמטית מצוינת (0% חשיפה לבנייה כרגע). אבל מוסיפה leverage risk לתיק שכבר סובל מ-IBIT בגודל שאינו תקין. ה-net diversification benefit קיים אבל לא מספיק לכסות על הבעיה המבנית.

---

## [3] שווי והקצאת הון

**אנליזת שווי (מהאנליסט):**

| תרחיש | EBITDA | EV/EBITDA | מחיר | שינוי |
|--------|--------|-----------|------|-------|
| 🔴 דובי | $220M | 5.5x | ~$0.33 | -99% |
| 🟡 בסיס | $318M | 8.5x | ~$50 | +30% |
| 🟢 שורי | $340M | 11x | ~$83 | +112% |
| נוכחי | — | 7.4x | $38.65 | — |

**ציפיית תשואה משוקללת (עורך הדין השטן):** 7.5% — לא מרשים לסיכון הנדרש.

**עלות הזדמנות — 3 אפשרויות:**

| אפשרות | תיאור | R/R | עדיפות |
|--------|-------|-----|--------|
| **1. בניית מזומן** | מזומן נוכחי 3.6% — מתחת ל-5% מינימום. ריבית חסרת-סיכון ~4.3%. בזמן שהתיק לא מאוזן, מזומן = לא ריק, הוא אופציה לכניסה במחיר טוב לNOW ו-AMZN | 🟢 — מאבטח אפשרויות עתידיות | **ראשון** |
| **2. NOW — כבר APPROVED** | NOW מאושר ב-$100, כרגע ב-$124.37. מרחק 24.4%. כשיגיע לטריגר — קנייה ב-Growth layer (שצריך חיזוק), ב-SaaS enterprise עם R/R 2.2:1 מוגדר | 🟢 — R/R עדיף על ROCK בתרחיש בסיס | **שני** |
| **3. ROCK עכשיו** | 7.5% ציפיית תשואה, downside -43% בmiss 17%, entry ב-$38.65 (לא נקודת ערך מירבית לפי DA) | 🟡 — R/R סביר אבל לא מספיק לנוכח הסיכון | **שלישי** |

**פסיקת שווי:** ROCK אטרקטיבי **אם** execution מושלמת. אבל האנליסט והDA מסכימים שמחיר אטרקטיבי אמיתי הוא $26-28 (EV/EBITDA 5.8-6.2x עם buffer). ב-$38.65 — מחיר הוגן לתרחיש בינוני. לא bargain.

---

## [4] ביקורת סיכון התנהגותי

**כרטיס ניקוד הטיות:**

| הטיה | זוהה? | עוצמה | פירוט |
|------|-------|-------|-------|
| FOMO | ✅ | 🟡 בינונית | מניה ירדה 48% מהשיא — "פספסת את השיא, אל תפספס את הבסיס" — הטיה שכיחה בירידות חדות |
| Revenge Trade | ❌ | 🟢 לא קיים | אין פוזיציה קודמת ב-ROCK, אין הפסד לשחזר |
| Overconfidence | ✅ | 🟡 בינונית | "9.56x P/E = זול" — מספר אחד יוצר אשליית ביטחון. DA הסביר: P/E מבוסס Adj EPS שאינו GAAP ואינו מגובה FCF |
| Narrative Bias | ✅ | 🟡 בינונית | "מנהיגות שוק בגגות + CEO שקונה מניות = הנהלה מאמינה" — נרטיב משכנע מהמספרים |
| הטיית אישור | ✅ | 🟡 בינונית | שני הסוכנים הקודמים מצאו דגלים חמורים; תמריץ לחפש רק את הממצאים החיוביים |
| הטיית עדכניות | ❌ | 🟢 לא קיים | ניתוח מבוסס על שלושה שנות נתונים, לא רק מחיר אחרון |
| הטיית סמכות | 🟡 | 🟡 קלה | "2 אנליסטים נותנים $68 target" — sample קטן מאוד, לא קונצנזוס |

**שאלות חובה:**

**1. למה עכשיו דווקא?**
Q2 2026 (אוגוסט) הוא ה-moment of truth. כניסה לפני Q2 = קנייה לפני confirmation. אין קטליזטור מידי שמצדיק כניסה היום.

**2. האם הייתי מקבל אותה החלטה אם המניה לא זזה השבוע?**
מחיר נוכחי $38.65 vs 52W high $75.08 — המניה ירדה 48%. חלק משמעותי מהאטרקטיביות נובע מהירידה החדה, לא מאנליזה עצמאית של שווי.

**3. האם אני יכול להסביר את התזה מבלי לצטט אחרים?**
"Gibraltar רכשה OmniMax במחיר הגיוני, תדלברג ב-24 חודשים, ותרוויח פרמיית מכפיל" — תזה ברורה. אבל מבוססת על 5 הנחות שחייבות להתממש בו-זמנית.

**4. מה יגרום לי להודות שטעיתי?**
Kill switches ברורים: leverage >4.75x, EBITDA <$245M, FCF שלילי לרבעון שני ברציפות.

**🚨 מפסק זרם: לא מופעל** — אין FOMO קיצוני, אין revenge trade. אבל **תשומת לב מוגברת** לhטיות valuation ו-narrative bias.

---

## [5] מנוע גודל פוזיציה

```
שכנוע: בינוני (CEO, לא גבוה)
   → R/R 7.5% ציפויה (לא מרשים)
   → תלוי ב-Q2 2026 שעוד לא פורסם

סיכון: גבוה
   → Leverage 3.9x
   → $20M מזומן
   → $1.7B אינטנגיבלים
   → Housing market uncertain

שכנוע בינוני + סיכון גבוה → הפחתה 60%

מקסימום שכבת ספקולציה: 4%
× 40% (לאחר הפחתה) = 1.6%
```

**אבל:** השכבה מלאה. Speculation כבר 16.3%.

**חישוב מתמטי סופי:**
```
מקסימום טכני (אם השכבה הייתה פנויה): 1.6-2% ($31-39)
מקסימום בפועל (שכבה מלאה): 0% עד שמתבצע קיצוץ
```

**מסקנה:** גודל פוזיציה = **0% כרגע**. לאחר רה-בלנסינג ואישור Q2 — 2% מקסימום.

---

## [6] לוגיקת איזון מחדש

**הבעיות המבניות לפני ROCK:**

| בעיה | פוזיציה | מצב נוכחי | יעד | פעולה |
|------|---------|-----------|-----|-------|
| 🔴 IBIT חורגת פי 2.5 | IBIT Speculation | 10.0% | 4% max | מכירה של 6% ($119) |
| 🔴 NVDA מעל מקסימום | NVDA Growth | 13.3% | 12% max | מכירה של 1.3% ($25.8) |
| 🔴 ספקולציה גבוהה | Layer Total | 16.3% | 5-10% | כרוך בIBIT trim |
| 🔴 מזומן נמוך | Cash | 3.6% | 5-10% min | חלק מהמכירות → מזומן |
| 🔴 Growth נמוך | Layer Total | 49.3% | 55-65% | חלק מהמכירות → Growth |

**תוכנית איזון ספציפית (לפני כניסה לROCK):**

**שלב 1 — IBIT:** מכירה של $119 (6% מהתיק)
- IBIT עם P&L +215% — רווח ממומש משמעותי
- חלוקת תמורה: $50 → מזומן (Cash ל-6%), $69 → NOW כשיגיע לטריגר

**שלב 2 — NVDA:** מכירה של $25 (1.3% מהתיק)
- NVDA עם P&L +20.2% — רווח סביר
- תמורה: $25 → מזומן (Cash ל-7.3% לאחר שני הצעדים)

**לאחר שני הצעדים:**
| שכבה | לאחר רה-בלנסינג | יעד |
|------|-----------------|-----|
| Growth | 48.0% (+ NOW בעתיד) | מכוון ל-55-65% עם NOW |
| Stability | 30.7% | 🟢 תקין |
| Speculation | 9.7% (IBIT 3.7%+OKLO+APLD) | 🟢 בתוך יעד |
| Cash | 7.3% | 🟢 תקין |

**רק לאחר שלב זה — ניתן לשקול ROCK.**

---

## [7] החלטת CEO סופית

### ⬛ WAIT

**מניעים לאי-כניסה עכשיו:**

1. **מבנה תיק אוסר** — ספקולציה ב-16.3% (יעד 10%). כניסה לפני קיצוץ IBIT = החמרת הפרה.
2. **Q2 2026 הוא moment of truth** — אוגוסט 2026 יוכיח או יפריך את כל התזה. כניסה לפני = ספקולציה על ספקולציה.
3. **מחיר לא אטרקטיבי מספיק** — $38.65 הוא "הוגן לבסיס". DA ואנליסט מסכימים: $26-28 הוא ה-bargain האמיתי. מרווח ביטחון שולי.
4. **עדיפות ל-NOW** — כבר APPROVED, ב-Growth layer (חסרה), מחכה לטריגר.

---

## תוצאות ③-⑯

**① פסיקת CEO:** WAIT

**② ציון התאמה לתיק:** 4/10
*(דיברסיפיקציה תמטית מצוינת — 0/10 ב-Layer Fit)*

**③ שיוך שכבה:** Speculation — מינוף 3.9x, $20M מזומן, binary outcomes.

**④ המלצת גודל פוזיציה:**
```
כרגע:           0%
לאחר תנאים:     2% ($39.72)

חישוב:
→ שכנוע בינוני × סיכון גבוה = הפחתה 60% ממקסימום
→ מקסימום שכבה: 4%
→ 4% × 40% = 1.6% → עיגול ל-2% (עם buffer)
→ Constraint עורך דין שטן: max 4% — מאשר
→ Constraint שכבה: דורשת קיצוץ IBIT ראשית
```

**⑤ סיכון ריכוז:**
ROCK מוסיף דיברסיפיקציה תמטית אמיתית (building materials = תמה חדשה לחלוטין בתיק). אין חפיפה ל-AI/Tech/Crypto/Gold. חפיפה קלה עם VST/MU ברגישות מחזורית. **סיכון: leverage amplification בirisk-off scenarios** — בנפילת שוק, ROCK צפויה לרדת 1.4-1.8x S&P.

**⑥ החלטת שווי:** הוגן ב-$38.65 לתרחיש בסיס. אטרקטיבי רק ב-$26-28. עדיין לא bargain.

**⑦ עלות הזדמנות:**

| אפשרות | תשואה ציפויה | סיכון | עדיפות |
|--------|-------------|-------|--------|
| מזומן (4.3% חסר-סיכון) | 4.3% | 🟢 אפס | **ראשון — בניית אופציות** |
| NOW ב-$100 (Growth) | R/R 2.2:1 מוגדר | 🟡 SaaS מוכח | **שני — Growth Layer** |
| ROCK ב-$38.65 | 7.5% ציפוי | 🔴 Leverage binary | שלישי |

**⑧ ביקורת התנהגותית:**
FOMO מחיר (🟡 בינוני) + Narrative Bias (🟡 בינוני) — אין דגל אדום חמור, אבל שניהם מכוונים לקנייה יתרה. להמשיך בזהירות.

**⑨ מפסק זרם:** לא הופעל. אין FOMO קיצוני, אין revenge trade. **תנאי אזהרה פעיל:** Narrative + Valuation bias = לא להגדיל מעל 2% בשום תרחיש.

**⑩ המלצת איזון מחדש:** נדרש — לפני כל פעולה.

**תוכנית פעולה:**
1. **IBIT: מכור 6%** ($119) → Cash $50 + NOW queue $69
2. **NVDA: מכור 1.3%** ($25) → Cash $25
3. לאחר כן: Speculation = ~9.7%, Cash = ~7.3%, מבנה תקין

**⑪ 3 סיכוני תיק מובילים מהוספת ROCK:**

| # | סיכון | מנגנון |
|---|-------|--------|
| 1 | **Leverage Amplification בירידות** | ROCK Beta ~1.6 × Leverage amplification = בirisk-off, תוסיף ל-drawdown תיק בזמן הכי גרוע |
| 2 | **Covenant Breach = Zero** | אם EBITDA מאכזב 31% → Equity כמעט אפס. לא סיכון חלקי — binary total loss |
| 3 | **Goodwill Write-down Q4 2026** | $1.7B אינטנגיבלים (194% הון עצמי) → write-down $300-500M אפשרי → panic sell → ROCK מגדיל volatility תיק |

**⑫ הסיבה החזקה ביותר לא לבצע:**
שכבת הספקולציה ב-16.3% — **פי 1.6 מהתקרה המקסימלית**. קניית ROCK עכשיו היא הוספת ספקולציה על בעיה מבנית קיימת, לא קנייה מנוהלת. זה מפר את עקרון ניהול הסיכון הבסיסי של התיק.

**⑬ האמת הקשה:**
לפני ש-ROCK על הפרק — IBIT צריכה לרדת מ-10% ל-4%. חברת ביטקוין בגודל של פוזיציית Growth בתיק שמוגדרת Speculation היא הבעיה האמיתית. ROCK היא השאלה הנכונה על ההשקעה הבאה, אבל IBIT היא השאלה שצריכה לבוא קודם.

**⑭ ציון שכנוע סופי:** 5/10
*(עסק מעניין, מחיר מתקדם, קטליזטורים מוגדרים — אבל timing ומבנה תיק לא תומכים)*

**⑮ החלטה סופית:**

### ⬛ WAIT

פעולה ספציפית הבאה: **בצע קיצוץ IBIT (6% → 4%) לפני כל דיון נוסף על ROCK**. לאחר IBIT טריפ ו-Q2 2026 results (אוגוסט 2026), החזר ROCK לוועדה עם תנאי מינימום: (1) Adj EBITDA Q2 ≥ $85M, (2) Gross Margin >24%, (3) FCF חיובי, (4) Residential organic לא שלילי.

**⑯ שאלות חובה לפני ביצוע (לכשהתנאים יתמלאו):**

- **מהי התזה במשפט אחד?** Gibraltar תמחיש deleveraging מ-3.9x ל-2.5x תוך 24 חודשים דרך OCF ייצור + OmniMax synergies, ומכפיל EV/EBITDA יעלה מ-7.4x ל-9-10x ב-re-rating.
- **מה מוכיח שטענו?** Q2 2026: FCF חיובי + Gross Margin >24% + Residential organic ≥ -1%.
- **האם היינו קונים עוד אחרי -25%?** ב-$29 (עם Net Leverage יציב) — כן. ב-$29 עם Leverage עולה — יציאה מיידית.

---

```dashboard-json
{
  "ticker": "ROCK",
  "date": "2026-06-01",
  "verdict": "WAIT",
  "score": 4,
  "thesis": "Gibraltar (ROCK) היא עסק בנייה איכותי שביצע הימור ממונף (OmniMax $1.335B, leverage 3.9x) בשוק דיור שטרם התאושש. מחיר 9.56x P/E נראה זול אך מוטה בAdj EPS; downside -43% בmiss 17%, covenant breach בmiss 31%. WAIT עד Q2 2026 + קיצוץ מוקדם של IBIT.",
  "key_risks": [
    "שכבת ספקולציה ב-16.3% (פי 1.6 מהתקרה) — אין מקום מבני ל-ROCK ללא קיצוץ IBIT קודם",
    "Covenant breach: EBITDA miss 31% → Net Leverage >5.25x → equity כמעט אפס — סיכון binary לא חלקי",
    "Q2 2026 טרם פורסם — כניסה לפני תוצאות = ספקולציה על ספקולציה ללא confirmation",
    "Goodwill $1.7B = 194% הון עצמי — write-down Q4 2026 אפשרי אם OmniMax מאכזב",
    "מחיר $38.65 הוגן לבסיס אבל לא bargain אמיתי; $26-28 הוא ה-entry האטרקטיבי"
  ],
  "position_size_pct": 0,
  "valuation_summary": "שווי הוגן בסיס $50 (+30%), שורי $83 (+112%), דובי $13-22 (-43-66%). Entry אטרקטיבי: $26-28. נוכחי $38.65 = הוגן לבסיס בלבד.",
  "entry_exit_plan": "0% כרגע. תנאי כניסה: (1) קיצוץ IBIT ל-4% תחילה, (2) Q2 2026 מאשר FCF חיובי + Gross Margin >24% + EBITDA Q2 ≥$85M, (3) מחיר ≤$35 עדיף. כניסה: 2% ($39). Stop loss: $29 (leverage escalation). יעד בסיס: $50.",
  "handoff_summary": "CEO סיים ניתוח ROCK עם פסיקת WAIT מטעמי מבנה תיק. שכבת הספקולציה ב-16.3% (יעד 5-10%) אוסרת כניסה ללא קיצוץ IBIT (10%→4%) תחילה. לאחר רה-בלנסינג ו-Q2 2026 (אוגוסט 2026) — אם EBITDA ≥$85M, FCF חיובי, Gross Margin >24% — אפשרי לאשר 2% ב-Speculation. הסוכן הבא: Executor — לבצע קיצוץ IBIT כשלב ראשון בלבד, לא כניסה ל-ROCK."
}
```
