# מבצע — Ferrari N.V. (RACE) | 2026-06-01

---

## אימות קלטים

| קלט | סטטוס | פרטים קריטיים |
|-----|-------|--------------|
| HANDOFF אנליסט | ✅ | ציון 8.0/10, שווי בסיס $378, דובי $255, שורי $480, מחיר $345 |
| HANDOFF עורך דין שטן | ✅ | ציון סיכון 5/10, סיכון שלילי -26% (דובי) / -47% (אסון), מקסימום 8% = $159 |
| HANDOFF CEO | ✅ | פסיקה: WAIT, גודל מאושר: 4% ראשוני ($79), שכבה: Growth, מימון: ריאורגון IBIT בלבד |

כל שלושת הקלטים תקינים. ממשיך לניתוח ביצוע.

---

## טבלת נתוני ביצוע — RACE

נתונים שנאספו בסשן זה (תצפיות 490-495). מקורות: Finviz, Yahoo Finance. פערים מסומנים.

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
נתוני ביצוע — RACE
מקור: Finviz (אוטומטי, סשן נוכחי) + Yahoo Finance
תאריך: 2026-06-01
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

מחיר נוכחי: $345.00
52W High: $519.10 | Low: $312.51

--- ממוצעים נעים ---
20DMA: ⚠️ לא זמין — מוערך $338-348 (מחיר ~0% ביחס)
50DMA: ⚠️ לא זמין — מוערך $420-440 (מחיר ~20-22% מתחת)
200DMA: ~$384 (מחיר 10.17% מתחת) ✅ מאומת Finviz

--- מומנטום ותנודתיות ---
שינוי 5 ימים: ⚠️ מוערך -8% עד -10% (Luce announcement 25/5/2026)
שינוי חודש: ⚠️ מוערך -15% עד -20%
RSI(14): 53.89 ✅ מאומת Finviz
ATR(14): ⚠️ מוערך $13-15 (אחרי יום Luce -8.4%)
חוזק יחסי מול S&P (30 יום): ⚠️ לא זמין — מוערך נחות (RACE -15-20% vs SPY יציב)

--- נפח ---
נפח יומי ממוצע (30 יום): ⚠️ לא זמין
נפח אחרון (5 ימים): ⚠️ לא זמין — נפח Luce ביום likely גבוה מאוד
יחס נפח: ⚠️ לא זמין

--- רמות מבנה ---
רמת תמיכה 1: $312.51 (שפל 52 שבועות — תמיכה מבנית קריטית)
רמת תמיכה 2: ⚠️ לא זמין swing lows ספציפיים
רמת התנגדות קרובה: ~$384 (200DMA דינמי)

--- אירועים ושוק ---
תאריך דוח הבא: 30 יולי 2026 (Q2 2026) ✅ מאומת
ימים עד דוח: ~59 ימים
EPS קונסנזוס Q2 2026: ⚠️ לא זמין ספציפית (FY2026 ≥$9.45 הנחיה)
תוצאת דוח אחרון: Q1 2026 — Beat (הכנסות +3.2%/+6% CC, FCF +5%)

VIX נוכחי: 15.42 ✅ מאומת
S&P 500 מול 200DMA: מעל — SPY $757.06 vs 200DMA ~$673-722 ✅ מאומת

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️ פערי נתונים: ATR, 20DMA, 50DMA, נפח — מוערכים בלבד.
כל מספרים מוערכים אינם לשימוש בהחלטת ביצוע מדויקת — רק לכיוון כללי.
נדרש Finviz עדכני לפני ביצוע בפועל.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

---

## [1] פילטרים קשיחים

### פילטר תזמון דוח

- ימים עד Q2 2026: **~59 ימים** (30 יולי 2026)
- 59 ימים > 14 ימים: ✅ **עובר — חוקי ביצוע רגילים חלים**

הערת מבצע: טכנית הפילטר עובר. אך ה-CEO הגדיר את Q2 2026 כ**אירוע בינארי** שקובע את הכניסה — לא חסם אלא **טריגר**. הפסיקה היא WAIT עד Q2, לא בגלל קרבה לדוח (59 ימים) אלא כי הדוח הוא נקודת הבהרת Luce הראשונה.

**סטטוס**: ✅ עובר פילטר | 🟡 מסומן כטריגר אסטרטגי

---

### פילטר מומנטום

- שינוי 5 ימים: מוערך **-8% עד -10%** (Luce announcement 25/5/2026)
- המניה בירידה, לא בעלייה
- פילטר ה-FOMO (>15% עלייה) **לא מופעל**

הערת מבצע: הדינמיקה הפוכה — לחץ מכירה. אין רדיפת מחיר. ✅

**סטטוס**: ✅ עובר

---

### פילטר RSI

- RSI(14): **53.89**
- טווח בריא: 40-65
- RSI 53.89 = **אזור בריא לחלוטין**

הערת מבצע: RSI אינו מצביע על קנייתֵר (>70) ולא על חולשה קיצונית (<30). מניה שירדה 33.5% מהשיא עם RSI 54 — מצביע על ירידה מתונה ומסודרת, לא על פאניקה. זה בריא לתהליך בסיס-בניה אפשרי. ✅

**סטטוס**: ✅ עובר

---

### פילטר הרחבה (>15% מעל 50DMA)

- 50DMA: מוערך ~$420-440
- מחיר $345 = **~20-22% מתחת** ל-50DMA (מוערך)
- גם מ-200DMA: 10.17% מתחת

המניה נמצאת בתת-ביצוע חד מתחת לממוצעים — **ההפך מ"מורחבת"**. 🟡

**סטטוס**: ✅ עובר (אין סיכון פריצת-over)

---

### פילטר אישור נפח

- נתוני נפח: ⚠️ לא זמינים מהמקורות שנסרקו
- ידוע: יום Luce (25/5/2026) — ירידה -8.4% הרגישה כירידה על נפח גבוה (הפצה)
- כניסה בפולבק/בדשדוש: נפח נמוך **תקין** לפי חוקי הפילטר

**סטטוס**: ⚠️ לא רלוונטי (אין פריצה לאשר; כניסה תהיה בפולבק או דשדוש)

---

### פילטר משטר שוק

- VIX: **15.42** (< 18) ✅
- SPY מעל 200DMA: ✅ ($757.06 vs ~$695 200DMA)
- **Risk-On מאושר בשני קריטריונים**

**סטטוס**: ✅ עובר — Risk-On

---

### פילטר שווי בכניסה

- מחיר נוכחי: $345
- שווי הוגן בסיס (אנליסט): $378
- מרחק: ($378-$345)/$378 = **8.7% מתחת לבסיס**
- סיווג: הוגן (מתחת ל-10% מתרחיש בסיס ✅)

⚠️ **הסתייגות קריטית**: עורך הדין השטן הוכיח שה-Expected Value = $345.89 ≈ מחיר נוכחי. המניה "הוגן" לא כי יש מרווח ביטחון אלא כי **השוק כבר מגלם את הבסיס**. הוגן אינו אטרקטיבי.

**סטטוס**: 🟡 עובר טכנית | אין margin of safety

---

### סיכום פילטרים

| פילטר | סטטוס | הערה |
|-------|-------|------|
| תזמון דוח | ✅ עובר | 59 ימים > 14; Q2 = טריגר לא חסם |
| מומנטום | ✅ עובר | ירידה, לא FOMO |
| RSI | ✅ עובר | 53.89 — בריא |
| הרחבה | ✅ עובר | מתחת ל-50DMA, לא מורחב |
| אישור נפח | ⚠️ לא רלוונטי | כניסת פולבק, נפח נמוך תקין |
| משטר שוק | ✅ Risk-On | VIX 15.42, SPY מעל 200DMA |
| שווי | 🟡 הוגן-גבולי | EV = מחיר נוכחי; אין edge |

**סיכום**: **6 מ-6 פילטרים עוברים** — אבל הפסיקה היא עדיין WAIT. הפילטרים הם תנאי הכרחי, לא מספיק. ה-R/R (0.37:1) ואירוע הבינארי הלא-פתור הם הגורמים הקובעים.

---

## [2] הערכת משטר שוק

**סיווג: Risk-On**

| מדד | ערך | סף | סטטוס |
|-----|-----|-----|-------|
| VIX | 15.42 | < 18 = Risk-On | ✅ |
| SPY מול 200DMA | ~9% מעל | > 0% = Risk-On | ✅ |

**סיווג**: Risk-On — **שניים מתוך שניים**

**השלכות ביצוע**: בסביבת Risk-On, מהירות פריסה מלאה מקובלת מבחינה טכנית. אך ה-CEO הגדיר WAIT מסיבות שאינן קשורות למשטר שוק (R/R, binary event, מבנה תיק). משטר שוק חיובי הוא גורם **מאפשר**, לא **מחייב** כניסה.

**שאלה מרכזית**: "האם הסביבה הנוכחית תומכת בפריסה אגרסיבית?"
**תשובה**: הסביבה תומכת — אבל הנכס הספציפי לא מצדיק אותה ב-$345.

---

## [3] איכות פעולת מחיר

**דירוג: חלש — 3/10**

| קריטריון | מצב | הערכה |
|---------|-----|-------|
| קונסולידציה 2-6 שבועות (טווח צר) | ❌ יום Luce לפני 7 ימים; אין עדיין בסיס | חלש |
| מחזיק 50DMA + 200DMA | ❌ מתחת לשני הממוצעים | חלש |
| חוזק יחסי מול שוק | ❌ מוערך נחות בבירור (RACE -15-20% vs SPY יציב) | חלש |
| RSI 40-65 | ✅ 53.89 — בריא | חיובי |
| נפח יורד בפולבקים | ⚠️ לא זמין | לא ידוע |
| היווצרות בסיס בריאה | ❌ טרם | חלש |
| מרחק מ-52W Low | $345 vs $312.51 — 10.4% מעל | 🟡 קרוב לתחתית |

**ממצאים מרכזיים**:
- המניה בירידה מסודרת מ-$519 — לא קריסה, אבל לא ייצוב
- RSI 53.89 ב-$345 (אחרי ירידה של 33.5%) = **אין תמיכה טכנית אמיתית** — הביקוש לא נכנס
- 52W low ב-$312.51 הוא רמת התמיכה המבנית הקריטית היחידה הברורה
- אין ניסיון בסיס, אין קונסולידציה, אין VWAP anchoring מחדש
- 200DMA ב-$384 הפך מתמיכה להתנגדות

**זיהוי רמות תמיכה לתמחור טראנשים**:

| רמה | מחיר | מקור | איכות |
|-----|------|------|-------|
| תמיכה עיקרית | $312.51 | 52W Low מבנית | 🟢 חזקה — מבנה |
| תמיכה דינמית 200DMA | $384 | ממוצע נע | 🔴 עכשיו התנגדות |
| אזור כניסה מועדף | $310-325 | קרוב ל-52W Low | 🟢 אזור ביקוש |
| התנגדות ראשונה | $384 (200DMA) | ממוצע דינמי | 🔴 |
| התנגדות שנייה | $440+ (50DMA מוערך) | ממוצע דינמי | 🔴 |

**שאלה מרכזית**: "האם אנחנו קונים חוזק או רודפים אחרי אופוריה?"
**תשובה**: לא אופוריה — אבל גם לא חוזק. אנחנו מסתכלים על **ירידת-מחיר שמחפשת תמיכה** ב-52W low. הכניסה האופטימלית: לאחר שה-52W low תיבדק ותחזיק, עם קטליזטור (Q2 2026).

---

## [4] אישור נפח

**סטטוס: נעדר (נתונים לא זמינים)**

| תצפית | ממצא | מקור |
|-------|------|------|
| נפח ממוצע 30 יום | ⚠️ לא זמין | Finviz לא נסרק לנפח |
| נפח יום Luce (25/5) | ↑ מוערך גבוה (-8.4% = נפח הפצה) | הסקה מתנועת מחיר |
| יחס נפח נוכחי | ⚠️ לא זמין | — |
| אותות צבירה/הפצה | ⚠️ לא אמינים ללא נתון | — |

**אבחון**: ירידה של 8.4% על חדשות מוצר בדרך כלל מביאה נפח גבוה = **אות הפצה** (מוסדיים מוכרים). עד שנתוני נפח מאשרים צבירה מחודשת — **נחות-ברירת מחדל לנפח**.

פריצה מהדשדוש העתידי (כניסה לאחר Q2) תדרוש אישור נפח ≥ 1.5x לפני כניסת טראנש 2.

---

## [5] שווי בכניסה וסיכון/תשואה

### הצלבת שווי הוגן

| תרחיש | שווי ($) | מחיר $345 vs שווי |
|--------|---------|-----------------|
| שמרני (דובי) | $255 | +35.3% מעל = מחיר נוכחי יקר מהדובי |
| בסיס | $378 | -8.7% מתחת = "הוגן" |
| שורי | $480 | -28.1% מתחת = פוטנציאל משמעותי |
| אלפא | $531 | -35.0% מתחת = ספקולטיבי |

### חישוב R/R מלא (ב-$345)

```
עליה = ($378 - $345) / $345 = +9.6%
ירידה = ($255 - $345) / $345 = -26.1%

יחס R/R = 9.6% / 26.1% = 0.37:1
```

**🔴 מתחת לסף מינימלי 2:1 בפגישת מחיר**

### חישוב מחיר כניסה ל-R/R = 2:1

```
תנאי: (378 - P) / (P - 255) = 2
378 - P = 2P - 510
888 = 3P
P = $296
```

**מחיר לרשימת מעקב (2:1 R/R) = $296**

⚠️ **ממצא קריטי**: $296 נמוך מ-52W low ($312.51). כלומר, **R/R של 2:1 מחייב שבירת 52W low** — שהיא עצמה אות טכני שלילי. זה מלמד שבמחיר בסיס $378 ועם bear case $255, הנכס פשוט אינו מציע R/R מספק בשוק הנוכחי ב-$345.

### ניתוח R/R לאחר Q2 חיובי (הסיבה ל-WAIT)

אם Q2 2026 מאשר Luce order intake חיובי + הנחיות שמרו:

| תרחיש | הסתברות (כעת) | הסתברות (post-Q2+) | השפעה |
|--------|--------------|-------------------|-------|
| שורי $480 | 22% | 32% | ↑ |
| בסיס $378 | 40% | 50% | ↑ |
| דובי $255 | 28% | 12% | ↓ |
| אסון $184 | 10% | 6% | ↓ |

```
EV post-Q2 חיובי (בכניסה $315):
  $480 × 32% = $153.6
  $378 × 50% = $189.0
  $255 × 12% = $30.6
  $184 × 6%  = $11.0
  ──────────────────
  EV = $384.2

תשואה צפויה: ($384.2 - $315) / $315 = +22.0%
```

**מסקנה**: הסבלנות עד Q2 מחזירה expected value של +22% במקום +0.3% עכשיו. זוהי הצדקה כמותית ל-WAIT.

### סיווג כניסה

**ב-$345**: **הוגן-גבולי** — EV = מחיר נוכחי
**ב-$315 post-Q2**: **הוגן** — EV +22% (בהנחת Q2 חיובי)
**ב-$296**: **אטרקטיבי** — R/R מגיע ל-2:1 (אך כנראה מחייב שבירה טכנית)

---

## [6] מבנה ביצוע

**פסיקה: המתן**

**סיבות ספציפיות לדחיית כניסה עכשיו**:

1. **R/R 0.37:1** — מתחת לסף מינימלי 2:1 בפגישת מחיר. כל כניסה ב-$345 היא כניסה לנכס בתמחור-מדויק בלי מרווח ביטחון.

2. **ביצוע עיוור לאירוע בינארי** — Q2 2026 (59 ימים) הוא **הנקודה היחידה** שבה הנהלה תדבר על Luce order intake. הכניסה עכשיו משמעה תשלום מחיר מלא עם אי-ודאות מקסימלית לגבי ה-moat.

3. **מבנה תיק מונע** — Cash 3.6% (מתחת לרצפת 5%), כניסה מיידית תאפס מזומן. אסור מבחינה מבנית.

**תנאי הפעלת כניסה (כולם נדרשים)**:

| תנאי | מדד | סף |
|------|-----|-----|
| Q2 2026 earnings | Luce order intake + EBIT margin + guidance | Luce = חיובי, margin ≥29%, guidance maintained |
| שוק | VIX + SPY | Risk-On or Neutral (VIX < 25) |
| מחיר | אזור כניסה | $280-335 (עדיף $310-320) |
| תיק | Cash לאחר IBIT rebalance | ≥ 5% לאחר כניסה |

---

## [7] תוכנית ביצוע (מותנית)

### שלב 0 — מיידי (IBIT Rebalance — לפני כל כניסה ל-RACE)

```
פעולה: מכירת IBIT עודף
  מ: 10% = ~$198.62
  ל:  4% = ~$79.45
  שחרור מזומן: ~$119.17

תוצאה:
  Cash: $71.00 + $119.17 = $190.17 (9.6%)  ✅
  Spec:  16.3% → 10.3%  ✅ (קרוב ליעד)
  RACE:  0%  → ממתין לטריגר Q2
```

### שלב 1 — כניסה ראשונית (מותנה בטריגר Q2, ~30 יולי 2026)

**מבנה Scale In:**

```
───────────────────────────────────────────
טראנש 1: 40% מהפוזיציה המאושרת
  גודל: 1.6% מהתיק = ~$32
  סוג פקודה: LIMIT
  מחיר כניסה: $320 או טוב יותר
  אזור כניסה: $310 – $325
  תנאי: Q2 2026 earnings מאשר שלושת הקריטריונים +
         מחיר אינו עולה >3% מהתקרה המצוינת

  רציונל: כניסה ראשונה ב-52W Low Support Zone ($312.51)
  מבנה: ₪הנמוך מהאזור הזה = שבירה מבנית → stop מאחוריו

───────────────────────────────────────────
טראנש 2: 30% מהפוזיציה המאושרת
  גודל: 1.2% מהתיק = ~$24
  סוג פקודה: LIMIT
  תנאי טריגר: אחד מהבאים:
    א. פולבק ל-$310-315 שבועיים לאחר Q2 (אם כניסה הייתה גבוהה יותר)
    ב. שבוע שלישי post-Q2 בהיעדר שינוי תזה
  מחיר כניסה: $315 או טוב יותר

───────────────────────────────────────────
טראנש 3: 30% מהפוזיציה המאושרת
  גודל: 1.2% מהתיק = ~$24
  סוג פקודה: LIMIT
  תנאי טריגר: אישור תזה — RSI עובר מעל 60 + מחיר עולה מעל $360
  מחיר כניסה: $355 או פולבק ל-$340-350

סה"כ שלב 1: 4% = ~$80  (מימון: מזומן שחרר IBIT)
───────────────────────────────────────────
```

### שלב 2 — הרחבה (מותנה בנתוני Luce Q4 2026)

```
טראנש 4 (הרחבה): 4% נוסף = ~$80
  גודל: 4% מהתיק
  תנאי טריגר: Luce deliveries ≥ 300 יחידות ב-Q4 2026
               + ביטולי הזמנות < 5% על כל הדגמים
  מחיר כניסה: שוק (לא לרדוף — LIMIT ב-VWAP של היום)
  תאריך הערכה: ינואר 2027 (לאחר Q4 2026 report)

סה"כ שלב 1+2: 8% = ~$159 (מקסימום DA)
```

### רמת עצירה (ATR Method)

```
בסיס חישוב לכניסה ב-$315:
ATR(14) מוערך: $13 (⚠️ לאמת ב-Finviz לפני ביצוע)

שיטה א (ATR):
  Stop = $315 − (2.0 × $13) = $315 − $26 = $289

שיטה ב (מבנה):
  תמיכה מבנית: $312.51 (52W Low)
  Stop מבני: $300 (מרווח $12 מתחת לשפל)

השמרני מביניהם: $289 (ATR) — כלל השמרני חל

רמת עצירה מוצעת: $289
⚠️ ניואנס: $289 נמוך מ-52W low ($312.51) בכוונה —
   שבירה של ה-52W low עצמה (ל-$305) אינה מחייבת יציאה,
   אלא התנהגות מחיר מתחת ל-$289 כסגירה יומית.

סיבה: 52W Low הוא מרמה תמיכה, לא קו ביצוע. ATR מכבד
       את התנודתיות הטבעית ולא מאפשר "קטיף" ברעש.
```

### אופק זמן

```
אופק השקעה:    18-24 חודשים
טריגר ביניים:  Q2 2026 (30/7) — Luce order intake
טריגר ראשי:    Q4 2026 — Luce deliveries
תאריך בדיקה:   ינואר 2027 (שקילת הרחבה לשלב 2)
```

### כללי פקודה

- **LIMIT בלבד** — אסור פקודות שוק
- אם RACE זז >3% מעל $320 ביום Q2 earnings (gap-up) — **לא לרדוף**; המתן לפולבק
- **אסור בחלון הדוח** (יום לפני + יום אחרי Q2): פקודת שוק / MARKET
- אם VIX קופץ מעל 25 בין היום לבין Q2: הפחת טראנש 1 ל-50% (פוזיציה ראשונה קטנה יותר)

---

## פלט סופי

---

**① פסיקת מבצע**: **המתן**

---

**② ציון איכות כניסה: 3/10**

המניה בירידת-מגמה מ-$519 ל-$345, מתחת לשני הממוצעים הנעים המרכזיים, ללא קונסולידציה ולאחר מכירת-שוק קשה (Luce, -8.4%). RSI 53.89 הוא היחיד שמצביע על סדר — כל שאר האינדיקטורים מצביעים על setup חלש. אין רמת תמיכה ברורה מלבד ה-52W low ב-$312.51, שטרם נבדקה כתמיכה-ביקוש. נכס איכותי בסטאפ חלש — אין כניסה עכשיו.

---

**③ בדיקת פילטר קשיח: עבר עם סימונים**

| פילטר | תוצאה | אזהרה |
|-------|-------|-------|
| תזמון דוח | ✅ עובר | Q2 = טריגר, לא חסם |
| מומנטום | ✅ עובר | ירידה, לא FOMO |
| RSI | ✅ עובר | 53.89 — בריא |
| הרחבה | ✅ עובר | מתחת ל-50DMA |
| נפח | ⚠️ לא רלוונטי | נתונים חסרים |
| משטר שוק | ✅ Risk-On | VIX 15.42 |
| שווי | 🟡 הוגן-גבולי | EV = $345; אין edge |

**אזהרות שהופעלו**: שווי (EV = מחיר נוכחי, R/R 0.37:1) — **הופעל. טיפול: כניסה מותנית בשיפור R/R post-Q2**

---

**④ משטר שוק: Risk-On**

בסיס: VIX = 15.42 (< 18) / SPY $757.06 מעל 200DMA ~$695 (+9%)

---

**⑤ איכות פעולת מחיר: חלש**

- מתחת ל-200DMA (-10.17%) ומוערך מתחת ל-50DMA (בכ-20%)
- RSI 53.89 — אזור בריא, אך ניטרלי
- אין קונסולידציה או בסיס לאחר Luce sell-off (7 ימים בלבד)
- 52W low ב-$312.51 — תמיכה מבנית יחידה, טרם נבדקה
- מבנה: ירידת-מגמה מסודרת מ-$519; אין ניסיון-ייצוב עדיין

---

**⑥ אישור נפח: נעדר (נתונים לא זמינים)**

יחס נפח: ⚠️ לא ניתן לחשב — נתוני נפח לא זמינים ממקורות שנסרקו.
הסקה: יום Luce (25/5) — ירידה -8.4% על נפח מוגבר-סביר = אות הפצה.
עד שנתוני נפח יציגו צבירה, ברירת-מחדל: חוסר נפח.

---

**⑦ שווי בכניסה: הוגן (גבולי)**

נוכחי: $345 / שווי הוגן בסיס: $378 / פער: -8.7%
**מלכוד**: "הוגן" כי 8.7% מתחת לבסיס — אבל EV = $345.89 = מחיר נוכחי. אין מרווח ביטחון בפועל.

---

**⑧ סיכון דוח: נמוך**

ימים עד Q2 2026: **~59 ימים** (30 יולי 2026)
59 ימים = לא קרוב לדוח. אך Q2 הוא **הטריגר** לכניסה, לא סיכון להימנע ממנו.

---

**⑨ הערכת סיכון/תשואה: 0.37:1**

```
חישוב מלא ב-$345:
  עליה: ($378 - $345) / $345 = +9.6%
  ירידה: ($255 - $345) / $345 = -26.1%
  R/R = 9.6% / 26.1% = 0.37:1

מתחת לסף מינימלי 2:1 — פסיקה: WAIT (מאשר)

מחיר כניסה שבו R/R = 2:1:
  (378 - P) / (P - 255) = 2
  P = $296

⚠️ $296 נמוך מ-52W low ($312.51) — R/R "תקני" 2:1
   מחייב שבירת תמיכה מבנית, שהיא עצמה אות שלילי.
   
R/R post-Q2 חיובי (ב-$315, הסתברויות מעודכנות):
  EV = $384.2
  תשואה צפויה: +22.0%
  זו הצדקה כמותית ל-WAIT עד Q2.
```

---

**⑩ תוכנית ביצוע מומלצת**

```
שלב 0 (מיידי — לפני RACE):
  מכור IBIT: 10% → 4%
  שחרור: ~$119 → Cash: $190 (9.6%)

תוכנית כניסה (מותנית בQ2, ~30 יולי 2026):

טראנש 1:
  גודל: 1.6% = ~$32
  סוג פקודה: LIMIT
  מחיר: $320 או טוב יותר
  אזור: $310 – $325
  תנאי: Q2 earnings: Luce חיובי + EBIT ≥29% + guidance maintained

טראנש 2:
  גודל: 1.2% = ~$24
  סוג פקודה: LIMIT
  תנאי: פולבק ל-$310-315 (2 שבועות post-Q2) או יציבות 3 שבועות
  מחיר: $315 או טוב יותר

טראנש 3:
  גודל: 1.2% = ~$24
  סוג פקודה: LIMIT
  תנאי: RSI > 60 + RACE מעל $360 (אישור תזה)
  מחיר: $340-355

סה"כ שלב 1: 4% = ~$80
━━━━━━━━━━━━━━━━━━━━━━━
הרחבה (שלב 2, ינואר 2027):
  תנאי: Luce Q4 ≥ 300 יחידות + ביטולים < 5%
  גודל: 4% נוסף = ~$80
  סה"כ מקסימום: 8% = ~$159
━━━━━━━━━━━━━━━━━━━━━━━
סטופ ATR (כניסה $315):
  ATR(14) מוערך: $13 (לאמת לפני ביצוע)
  Stop = $315 − (2 × $13) = $289
  סיבה: $289 מתחת ל-52W low — שבירת תמיכה מבנית + ATR buffer
```

---

**⑪ רמת סיכון מוגדרת — מה הופך את הביצוע לגרוע אובייקטיבית**

| טריגר | סף | פעולה |
|-------|-----|-------|
| כניסה לפני Q2 | כל רכישה RACE לפני 30 יולי ללא Luce confirmation | ביצוע שגוי — הפסד edge מוחלט |
| Luce fail | <100 מסירות Q4 2026 | מכירה מיידית — kill switch |
| EBIT margin | <27% לשני רבעונים | צמצום ל-50% |
| מחיר שובר $289 | סגירה יומית מתחת לסטופ | יציאה מלאה — תיזה מבנית שבורה |
| Rebalance לא בוצע | כניסה RACE בלי מכירת IBIT קודם | Cash < 5% = הפרת חוקת תיק |

---

**⑫ טעות הביצוע הגדולה ביותר שאנחנו עשויים לעשות**

**לקנות Ferrari עכשיו בגלל שהיא Ferrari.**

הנרטיב "Ferrari = Hermès בתחפושת, FCF CAGR 19%, ספר הזמנות לסוף 2027" הוא כה שכנועי שהוא עלול להחליף את שאלת ה-R/R. זה Narrative Bias במיטבו: עסק מצוין בתחפושת השקעה מצוינת.

הטעות הספציפית: כניסה ב-$345 "כי המניה ירדה 34% ונראית זולה יחסית לשיא". $519 → $345 אינו "הנחה". זה תיקון שוק שאמר שה-P/E ב-$519 היה מוגזם. $345 עדיין מגלם ביצוע ללא פגם — ב-EV = מחיר נוכחי, $0.89 של Expected Value לכל $1 מושקע. זה הימור, לא השקעה.

הכלל: **איכות העסק אינה תחליף למחיר הכניסה. Ferrari ב-$345 ב-Luce binary event = תשלום מחיר מלא על אי-ודאות מקסימלית. הסבלנות היא ה-Alpha.**

---

**⑬ ביטחון סופי: גבוה**

ביטחון גבוה — **ב-פסיקת WAIT**. ה-R/R, ה-EV, ומבנה התיק מצביעים חד-משמעית על כניסה עכשיו כגרועה. הביטחון **ב-conditional entry plan** (post-Q2) הוא בינוני-גבוה — תלוי בתוצאות Q2.

---

## HANDOFF מבצע

```
---HANDOFF---
חברה: Ferrari N.V.
תאריך: 2026-06-01
תפקיד הושלם: מבצע

פסיקת ביצוע: המתן
ציון איכות כניסה: 3/10
משטר שוק: Risk-On (VIX 15.42, SPY מעל 200DMA)
סיכון/תשואה: 0.37:1 (ב-$345) | R/R = 2:1 ב-$296 | EV post-Q2+: +22% ב-$315

תוכנית ביצוע (מותנית, Q2 2026 trigger):
  שלב 0 (מיידי): מכור IBIT 10%→4%, שחרר $119, Cash → 9.6%
  טראנש 1: 1.6% ב-$320 (תנאי: Q2 = Luce חיובי + EBIT ≥29% + guidance)
  טראנש 2: 1.2% ב-$315 (תנאי: פולבק 2 שבועות post-Q2)
  טראנש 3: 1.2% ב-$345-355 (תנאי: RSI>60 + RACE מעל $360)
  הרחבה:   4% נוסף ב-ינואר 2027 (תנאי: Luce Q4 ≥300 יחידות)
סטופ ATR: $289 (2×ATR($13) מתחת לכניסה $315; מתחת ל-52W low)

סיכוני ביצוע מרכזיים:
- Narrative Bias: הנרטיב "Ferrari = Hermès" עלול לגרום לכניסה מוקדמת ללא R/R — המבצע מסמן זאת כסיכון ① 
- Luce binary event (Q2 2026): כניסה לפני 30 יולי = תשלום מחיר מלא על אי-ודאות מקסימלית
- R/R structurally limited: $296 (2:1) נמוך מ-52W low — Ferrari לא מציעה entry "תקני" בתמחור הנוכחי; Post-Q2 confirmation הוא הדרך היחידה לשיפור ה-EV

נתונים שסופקו: חלקי
פערי נתונים:
  - ATR(14): מוערך $13 — לאמת ב-Finviz לפני ביצוע
  - 50DMA ו-20DMA: לא זמינים — מוערכים
  - נפח יומי ממוצע + יחס נפח: לא זמינים
  - Luce cancellation rate: לא זמין (ייתכן שאינו גלוי עד Q2)
  - Q2 2026 EPS קונסנזוס: לא זמין ספציפית

הסוכן הבא: ועדת השקעות

שאלות פתוחות:
- האם ועדת ההשקעות מסכימה שכניסה $310-320 post-Q2 עם Luce חיובי מהווה R/R סביר (EV +22%)?
- האם התיק יאפשר 8% Growth נוסף (→53.3%) לאחר IBIT rebalance, בהינתן ריכוז מכפיל-פרמיום?
- אם RACE נסחרת מעל $340 ביום Q2 earnings (gap-up על beat), האם הוועדה מאשרת כניסה שם או רק בפולבק?

---סוף HANDOFF---
```

---

```dashboard-json
{
  "ticker": "RACE",
  "date": "2026-06-01",
  "verdict": "HOLD",
  "score": 3,
  "thesis": "Ferrari היא עסק 9/10 בסטאפ ביצוע חלש: R/R 0.37:1 ב-$345, EV = מחיר נוכחי, מתחת ל-200DMA, 59 ימים לפני אירוע בינארי (Q2 + Luce order data). WAIT עד 30 יולי 2026 עם כניסה מותנית ב-$310-320 אם Q2 מאשר Luce חיובי + EBIT recovery.",
  "key_risks": ["R/R structurally limited: 2:1 מחייב כניסה ב-$296 שנמוך מ-52W low; מחיר הוגן אינו מחיר אטרקטיבי", "Luce binary event לפני כניסה: Q2 2026 = הנקודה הראשונה לאמוד order intake; כל כניסה מוקדמת = תשלום מחיר מלא על אי-ודאות מקסימלית", "Narrative Bias: הנרטיב 'Ferrari=Hermès' עלול להחליף חישוב R/R — הסיכון הסובייקטיבי הגדול ביותר לביצוע", "מבנה תיק: IBIT rebalance חייב להקדים כל כניסה (Cash 3.6% < רצפת 5%)"],
  "position_size_pct": 0,
  "valuation_summary": "fair value $378 base (+9.6% from $345), bear $255 (-26%), bull $480 (+39%); EV@$345 = $345.89 — no edge; R/R 2:1 at $296; post-Q2 positive EV at $315 = +22%",
  "entry_exit_plan": "WAIT until Q2 2026 (July 30): Tranche 1 1.6%@$320 LIMIT / T2 1.2%@$315 / T3 1.2%@$345-355; stop $289 (2×ATR below $315 entry); expand to 8% on Luce Q4 deliveries ≥300 units",
  "handoff_summary": "המבצע מאשר פסיקת WAIT של ה-CEO ומגדיר תוכנית כניסה מדויקת. ניתוח R/R מגלה: $345 = EV מחיר שוק ללא edge; R/R 2:1 'תקני' מחייב כניסה ב-$296 שנמוך מ-52W low — פרדוקס שמלמד כי Ferrari בתמחור נוכחי פשוט אינה מציעה R/R מספק. Post-Q2 חיובי, EV משתפר ל-+22% ב-$315 עם probability distribution מעודכנת. פעולה מיידית: (1) מכירת IBIT 10%→4% לשחרור $119 ולהבאת Cash ל-9.6%; (2) הגדרת LIMIT order $320 להפעלה ביום Q2 earnings אם Luce order intake חיובי + EBIT margin ≥29% + guidance maintained; (3) סטופ $289 (ATR-based, מתחת ל-52W low). הסיכון הסובייקטיבי הגדול: Narrative Bias 'Ferrari=Hermès' עלול להניע כניסה מוקדמת — המבצע מסמן זאת במפורש."
}
```
