# CEO — AMZN | 28.05.2026 | $271.85

---

## [1] אימות קלטים

| קלט | סטטוס | הערה |
|-----|-------|------|
| Analyst Handoff | ✅ | ציון 6.8/10 — **ירידה מ-7.3/10 של אתמול** |
| Devil's Advocate Handoff | ✅ | ציון סיכון 7/10, EV $208.15 — **ירידה חדה מ-$260.9 של אתמול** |
| Portfolio Snapshot | ✅ | מלא, מעודכן ל-28.05.2026 |

כל שלושת הקלטים קיימים. ממשיכים.

---

## [2] דשבורד תיק — מבוסס על הנתונים שסופקו

```
═══════════════════════════════════════════════════════
תמונת מצב תיק נוכחית | 28.05.2026
═══════════════════════════════════════════════════════

סה"כ שווי:    $1,960.71

הקצאת שכבות:
```

| שכבה | קיים % | יעד % | סטטוס | פעולה נדרשת |
|------|--------|-------|-------|-------------|
| Stability | 30.2% | 25-35% | 🟢 תקין | אין |
| Growth | 49.2% | 55-65% | 🔴 נמוך | ניתן להוסיף — לא ב-$272 |
| Speculation | **16.9%** | 5-10% | 🔴 **חריגה קריטית** | **קצץ מיידי** |
| Cash | 3.6% | 5-10% | 🟡 נמוך | יגדל אחרי קיצוץ |

```
פוזיציות מובילות:
  1. NVDA     13.6% | Growth     | ⚠️ חורג מגבול 12%
  2. META     10.7% | Growth     |
  3. IBIT     10.3% | Speculation| 🔴 עיקר הבעיה
  4. GOOG     10.3% | Stability  |
  5. MSFT     10.1% | Stability  |

ריכוז תמתי:
  AI/Tech ישיר:  NVDA+META+GOOG+MSFT+MU+AVGO = 61.5%
  AI-adjacent:   VST+OKLO+APLD               = 14.8%
  Bitcoin:       IBIT                        = 10.3%
  זהב הגנתי:    GLDM                        =  9.9%
  מזומן:                                       3.6%

נדרש איזון מחדש: כן — דחוף ומיידי
  → Speculation 16.9% חורגת ב-6.9 נקודות מעל תקרה
  → NVDA 13.6% חורגת ב-1.6 נקודות מגבול פוזיציה (12%)
  → Cash 3.6% מתחת לרצפה 5%
═══════════════════════════════════════════════════════
```

---

## [3] מה השתנה מאתמול — השוואת מצב

**זהו שינוי מהותי:** אתמול IC ישב ב-$265.29. היום CEO מתבקש לאשר ב-$271.85.

| פרמטר | אתמול (IC) | היום (CEO) | כיוון |
|-------|-----------|-----------|-------|
| מחיר | $265.29 | $271.85 | 🔴 עלה $6.56 (+2.5%) |
| מרחק מטריגר | 15.3% | **18.2%** | 🔴 מתרחק |
| ציון אנליסט | 7.3/10 | **6.8/10** | 🔴 ירד |
| DA Expected Value | $260.9 | **$208.15** | 🔴 ירד $52.74 |
| FCF TTM | -$2.47B | -$2.47B | → ללא שינוי |
| Kill switch | נפרץ | **עדיין נפרץ** | 🔴 ללא שיפור |
| IBIT קיצוץ (המלצת IC) | נדרש מיידי | לא בוצע (עדיין 10.3%) | 🔴 לא בוצע |
| NVDA קיצוץ (המלצת IC) | נדרש מיידי | לא בוצע (עדיין 13.6%) | 🔴 לא בוצע |

**מסקנה קריטית: בכל מדד יחיד, המצב ב-28.05 גרוע יותר מ-27.05. שום דבר לא השתפר.**

---

## [4] בדיקת התאמה לתיק

**שיוך שכבה:** Growth

Growth נמצאת ב-49.2% מתחת ליעד 55-65% — יש מרחב תיאורטי. אבל:

**ניתוח חפיפה:**

| פוזיציה קיימת | חפיפה עם AMZN | מנגנון |
|--------------|---------------|-------|
| GOOG | 🔴 ישירה | GCP = מתחרה ישיר ל-AWS |
| MSFT | 🔴 ישירה | Azure = מתחרה ישיר ל-AWS |
| NVDA | 🔴 ישירה | Amazon קונה GPU מ-NVIDIA; Trainium = ניסיון ביטול |
| META | 🔴 ישירה | AI mega-spender, ירידה יחד ב-AI correction |
| MU | 🟡 עקיפה | Amazon לקוח HBM |
| AVGO | 🟡 עקיפה | AI networking, אותו capex cycle |
| VST | 🟡 עקיפה | Power provider ל-data centers |

**4 פוזיציות בחפיפה ישירה ל-AWS/AI.** הוספת AMZN אינה גיוון — היא הגברת ריכוז על תמה שכבר עומדת על 61.5%.

**AI/Tech עם AMZN 2%: 61.5% → 63.5%.** גיוון אפסי.

**דגל אדום:** ריכוז AI/Tech כבר ב-61.5%, מעל 3 פוזיציות דומות מאוד — דורש הצדקה יוצאת דופן להוסיף עוד.

---

## [5] שווי והקצאת הון

**מסגרת שווי (מ-Analyst):**

| תרחיש | שווי הוגן | מול $271.85 |
|--------|-----------|------------|
| 🔴 דובי | $108 | -60% |
| 🟡 בסיס | $224-256 | -7% עד -18% |
| 🟢 שורי | $320-360 | +18% עד +32% |

**EV מחושב (DA): $208.15 — המניה נסחרת ב-30.6% פרמיה לEV.**

**עלות הזדמנות — השוואת 3 חלופות:**

| חלופה | תשואה צפויה | סיכון | R/R | עדיפות |
|-------|------------|-------|-----|--------|
| **AMZN ב-$271.85** | EV $208 = -23% | גבוה (FCF שלילי, Azure) | 0.17:1 | 🔴 גרוע |
| **מזומן (risk-free)** | ~4.3-4.5% בטוח | כמעט אפס | — | 🟢 עדיף על AMZN עכשיו |
| **NOW ב-$102 (AT-TRIGGER)** | R/R 2.2:1, APPROVED | בינוני | 2.2:1 | 🟢 **עדיף מאוד** |

**החלטה:** מזומן ו-NOW עדיפים על AMZN ב-$271.85.

---

## [6] ביקורת התנהגותית

### כרטיס ניקוד הטיות:

| הטיה | זוהה? | עוצמה | ראיה |
|------|-------|-------|------|
| FOMO | **כן** | 🔴 גבוה | מחיר עלה $6.56 אתמול, CEO מוגש שוב — למה? |
| Revenge Trade | לא ברור | 🟢 | אין ראיה |
| Overconfidence | לא | 🟢 | — |
| Narrative Bias | כן | 🟡 | "AWS 28% + backlog $464B" עדיין מושך |
| הטיית סמכות | אפשרית | 🟡 | 66 אנליסטים Strong Buy, PT $312 |

### שאלות חובה:

1. **למה עכשיו דווקא?** המחיר עלה $6.56 מאז IC של אתמול. התנאים רעים יותר. מדוע CEO מתכנס היום?

2. **האם ההחלטה הייתה זהה אם המניה לא זזה השבוע?** המניה ב-52W High. +32% בשנה האחרונה. הBuy pressure הוא price-driven, לא thesis-driven.

3. **האם ניתן להסביר את התזה ללא ציטוט "AWS 28% ו-backlog $464B"?** קשה. זה נרטיב, לא מודל.

4. **מה יגרום להודאה שטעיתי?** Kill switches ברורים קיימים. אבל אחד כבר נפרץ ולא נפעלה פעולה.

**🔴 מפסק זרם: מופעל חלקית.**

**הפעלות:** FOMO זוהה (מחיר עלה, CEO מוגש שוב), המלצות IC של אתמול (IBIT + NVDA) לא בוצעו, מחיר עלה עוד יותר. **ההמלצה: השהיה 48 שעות על AMZN.** אם המחיר יאפשר לדון מחדש ב-$230 — נדון אז. לא עכשיו.

---

## [7] מנוע גודל פוזיציה

| פרמטר | ערך |
|-------|-----|
| שכנוע | נמוך-בינוני (FCF שלילי, kill switch נפרץ) |
| סיכון | גבוה |
| התאמה לתיק | חלש (ריכוז AI קיים) |
| → גודל מחושב | 0% (שכנוע נמוך = Watchlist בלבד) |

מקסימום לפי שכבה (Growth): 12%
מקסימום לפי DA: 4%
מקסימום לפי IC אתמול: 2.0%
**גודל CEO היום: 0%. לא בתנאים אלה.**

---

## [8] לוגיקת איזון מחדש — דחוף

**זו הפעולה הקריטית ביותר בתיק. לא AMZN.**

**בעיות קריטיות בתיק:**

1. **NVDA 13.6% — חריגה מגבול 12%:**
   - למכור: 1.6% × $1,960.71 = **$31.4**
   - תוצאה: NVDA → 12%, מזומן +$31.4

2. **Speculation 16.9% — חריגה קריטית מתקרה 10%:**
   - IBIT: 10.3% → יעד 4% = קיצוץ 6.3%
   - OKLO+APLD: 6.6% — בתוך יעד (ביחד עם IBIT ב-4%)
   - **IBIT למכור:** 6.3% × $1,960.71 = **$123.5**
   - תוצאה: Speculation → 10.6% (קרוב לגבול), Cash +$123.5

3. **לאחר הקיצוצים:**
   - Cash: $71 + $31.4 + $123.5 = **$225.9 (11.5%)**
   - יש מזומן לNOW (AT-TRIGGER, APPROVED): ~2% × $1,960 = $39.2
   - יש מזומן ל-AMZN כשיגיע ל-$230

**תוכנית איזון מחדש ספציפית:**

| פעולה | כמות למכור | מחיר משוער | תמורה |
|-------|-----------|-----------|-------|
| NVDA: 13.6% → 12% | 1.6% מהתיק | שוק | ~$31 |
| IBIT: 10.3% → 4% | 6.3% מהתיק | שוק | ~$124 |
| **סה"כ מזומן שיתפנה** | | | **~$155** |
| NOW ב-$102 (APPROVED, AT-TRIGGER) | 2.0% | $102 | -$39 |
| **Cash לאחר הכל** | | | **~$187 (9.5%)** |

---

## פלט נדרש

---

### ① פסיקת CEO: **WATCHLIST — ללא שינוי**

---

### ② ציון התאמה לתיק: **3/10**

ריכוז AI/Tech קיים 61.5%, Speculation 16.9% חורג, NVDA חורג. AMZN מגביר בעיות קיימות ולא מייצר value בתיק זה.

---

### ③ שיוך שכבה: **Growth**

---

### ④ המלצת גודל פוזיציה: **0% עכשיו | 2.0% ב-$230**

מחושב: DA מקסימום 4%, IC הוריד ל-2.0% בשל נקודה עיוורת. CEO מאמץ 2.0%.
תנאי כניסה: מחיר ≤$230 + Q2 AWS ≥25% + CapEx Q2 ≤$50B + IBIT כבר קוצץ.

---

### ⑤ סיכון ריכוז: **גבוה מאוד**

GOOG + MSFT + NVDA + META = 4 פוזיציות בחפיפה ישירה ל-AWS/AI.
בתרחיש AI correction -35%: NVDA -40%, META -35%, GOOG -30%, MSFT -25% + AMZN -35% = הפסד מצטבר -17% עד -22% על התיק. AMZN לא מגן — הוא מגביר.

---

### ⑥ החלטת שווי: **יקר**

EV $208.15 vs מחיר $271.85 = פרמיה 30.6%. Clean P/E ≈45x. FCF yield שלילי. אין margin of safety.

---

### ⑦ עלות הזדמנות: השוואת 3 חלופות

| # | חלופה | R/R | סיכון | עדיפות |
|---|-------|-----|-------|--------|
| 1 | מזומן + risk-free 4.4% | בטוח | נמוך | 🟢 עדיף על AMZN עכשיו |
| 2 | NOW ב-$102 (APPROVED, R/R 2.2:1) | 2.2:1 | בינוני | 🟢 **עדיפות ראשונה** |
| 3 | AMZN ב-$271.85 (EV $208) | 0.17:1 | גבוה | 🔴 אין alpha |

**פסיקה:** גם מזומן וגם NOW עדיפים על AMZN במחיר זה. NOW הוא ה-APPROVED item שמחכה לביצוע.

---

### ⑧ ביקורת התנהגותית

| הטיה | זוהה | עוצמה |
|------|------|-------|
| FOMO | כן | 🔴 גבוה — מחיר עלה, CEO מוגש מחדש יום למחרת |
| Revenge Trade | לא | 🟢 |
| Overconfidence | לא | 🟢 |
| Narrative Bias | כן | 🟡 — backlog $464B, AWS 28% משכנעים |

**אות FOMO ספציפי:** IC אתמול המליץ לקצץ IBIT+NVDA לפני כל כניסה לAMZN. שני קיצוצים אלו לא בוצעו, המחיר עלה $6.56, ו-CEO מוגש שוב. הדחיפות עולה כשהמחיר עולה — זו הגדרת FOMO.

---

### ⑨ מפסק זרם: **מופעל — השהיה 48 שעות על AMZN**

**מה הפעיל:**
- FOMO זוהה (מחיר עלה, הגשה חוזרת יום אחרי IC)
- המלצות IC של אתמול (IBIT + NVDA) לא בוצעו
- מחיר נע הפוך מהרצוי (עלה, לא ירד לטריגר)
- EV ירד מ-$260.9 לאתמול ל-$208.15 היום

**פעולה:** אין שינוי פסיקה. WATCHLIST. לחזור לAMZN רק אחרי: (א) IBIT קוצץ, (ב) NVDA קוצץ, (ג) מחיר ≤$230.

---

### ⑩ המלצת איזון מחדש: **נדרש — דחוף**

| פעולה | סיבה | דחיפות |
|-------|------|--------|
| IBIT: 10.3% → 4% | Speculation 16.9% חורגת | 🔴 מיידי |
| NVDA: 13.6% → 12% | חריגת גבול פוזיציה | 🔴 מיידי |
| NOW: כנס 2% ב-$102 | APPROVED, AT-TRIGGER, R/R 2.2:1 | 🟢 אחרי IBIT/NVDA |

---

### ⑪ 3 סיכוני תיק מובילים מהוספת AMZN

1. **ריכוז AI קיצוני:** AI/Tech עולה מ-61.5% ל-63.5%. 5 פוזיציות ב-correlation ≥0.7 לאותה תמה. בתרחיש AI selloff — אין diversification.

2. **FCF trap trajectory:** DA מחשב FCF FY2026 est. -$37B. כניסה עכשיו = holding חברה שתשרוף $37B מזומן השנה בתמחור $2.92T.

3. **Double leverage על Azure risk:** MSFT כבר 10.1% בתיק — אם Azure ממשיכה לנגוס בAWS, גם MSFT וגם AMZN ייפגעו. להפסיד על שניהם אינו גיוון.

---

### ⑫ הסיבה החזקה ביותר לא לבצע עסקה זו

**EV $208.15 מתחת למחיר $271.85 = מובנה בתמחור 30% הפסד.**

לא ירידה אפשרית. לא סיכון. **Expected value שלילי.** גם אם הכל ילך לפי התזה השורית, הסתברות 20% × (+$68) + יתר תרחישים = $208. משלמים $272. זה לא ניהול סיכונים — זה תמחור שגוי.

---

### ⑬ האמת הקשה

**התיק כבר "קנוי" על ההצלחה של AWS יותר מאמזון עצמה.**

GOOG, MSFT, NVDA, META, MU, AVGO — שש פוזיציות שמרוויחות ישירות מAWS competitive landscape ו-AI infrastructure cycle. אם backlog $464B ימומש, Trainium יצליח, ו-AI capex יחזיר ROI: שש הפוזיציות האלו כבר עולות. AMZN לא מוסיפה חשיפה — היא מכפילה חשיפה קיימת.

בנוסף: הוועדה של אתמול אמרה "קצץ IBIT+NVDA לפני AMZN." זה לא נעשה. הגשת CEO היום כשהמחיר עלה ו-IBIT לא קוצץ — זו עדות שהדחיפות לנכס חדש גוברת על הסדר הנכון. זה בדיוק ההתנהגות שמפסק הזרם נועד לעצור.

---

### ⑭ ציון שכנוע סופי: **3/10**

עסק: 8/10. מחיר: 2/10. התאמה לתיק: 2/10. ממוצע משוקלל: 3/10.

---

### ⑮ החלטה סופית: **WATCHLIST — ללא שינוי**

המחיר עלה $6.56 ביממה. EV ירד מ-$260.9 ל-$208.15. ציון האנליסט ירד מ-7.3 ל-6.8. מרחק מהטריגר גדל מ-15.3% ל-18.2%. לא נוצרה שום סיבה חדשה לכנוס. ההפך — כל מדד החמיר.

**פעולה ספציפית הבאה:** קצץ IBIT (10.3% → 4%), קצץ NVDA (13.6% → 12%), ביצע NOW ב-$102 (APPROVED, AT-TRIGGER). אלו שלוש הפעולות שיש לבצע לפני שAMZN נדון שוב.

---

### ⑯ שאלות חובה לפני ביצוע

1. **מהי התזה במשפט אחד?** "AWS+Ads יצמחו 22-28% ו-FCF יתאושש ב-2027-2028 ממחיר $230."
2. **מה מוכיח את זה?** backlog $364B RPO ו-28% Q1. מה שלא מוכח: conversion rate, FCF timeline, Trainium vs Blackwell.
3. **האם נקנה עוד אחרי -25% ($204)?** שאלה בינארית: אם FCF TTM הפך לפחות שלילי — כן. אם FCF עמוק שלילי עוד יותר — לא. הטריגר לא מבוסס על מחיר בלבד.

---

```dashboard-json
{
  "ticker": "AMZN",
  "date": "2026-05-28",
  "verdict": "WATCHLIST",
  "score": 3,
  "thesis": "AWS+Ads צומחים 22-28% עם backlog $464B, אך FCF TTM שלילי (-$2.47B), CapEx $173B שנתי, EV $208.15 מתחת למחיר $271.85 (-23.4%), ו-Azure גדלה מהר יותר ב-enterprise. מחיר עלה $6.56 מאז IC של אתמול — תנאים גרעו, לא השתפרו.",
  "key_risks": [
    "EV $208.15 מול מחיר $271.85: פרמיה 30.6% לEV, expected value שלילי בכל כניסה עכשיו",
    "FOMO זוהה: IC אתמול המליץ לקצץ IBIT+NVDA קודם — לא בוצע; CEO מוגש שוב כשמחיר עלה",
    "FCF trajectory: OCF ~$163B FY2026 est. מול CapEx $200B = FCF -$37B FY2026 — kill switch עמוק"
  ],
  "position_size_pct": 0,
  "valuation_summary": "EV $208.15, שווי הוגן בסיס $224-256. מחיר $271.85 נסחר ב-30.6% פרמיה לEV. כניסה מוצדקת רק ב-$230 עם תנאי Q2.",
  "entry_exit_plan": "0% עכשיו. T1 $230 (50%) + T2 $215 (30%) + T3 $200 (20%) = 2.0% סה\"כ. תנאי: מחיר ≤$230 + Q2 AWS ≥25% + CapEx Q2 ≤$50B + IBIT קוצץ קודם. Stop $187. TP1 $295, TP2 $370. Kill: FCF TTM < -$15B OR AWS YoY < 22%.",
  "handoff_summary": "CEO מאשר WATCHLIST ללא שינוי. כל מדד החמיר מ-IC של אתמול: מחיר +$6.56, EV ירד $52.74, ציון אנליסט ירד 0.5 נקודות, מרחק מטריגר גדל ל-18.2%. FOMO מופעל: המלצות IBIT+NVDA של IC אתמול לא בוצעו ו-CEO מוגש שוב — מפסק זרם 48 שעות הופעל. פעולה דחופה: (1) IBIT 10.3%→4%, (2) NVDA 13.6%→12%, (3) NOW ב-$102 (APPROVED, AT-TRIGGER, R/R 2.2:1). רק אחרי שלוש אלו — AMZN נדון שוב. סיכוי הגיון כניסה ל-AMZN: $230 + אישור Q2 2026 (30 יולי)."
}
```
