# החלטת CEO: AMZN
## 27 מאי 2026 | מחיר: $265.29 | שווי שוק: $2.85T

---

## [1] אימות קלטים

| קלט | סטטוס | נקודה מרכזית |
|---|---|---|
| Analyst Handoff | ✅ מלא | ציון 7.3/10, FCF TTM -$2.47B, backlog $464B |
| Devil's Advocate Handoff | ✅ מלא | ציון סיכון 7/10, EV $260.9 מתחת למחיר |
| Portfolio Snapshot | ✅ מלא | $1,958.14, 11 פוזיציות, Speculation 16.9% |

כל שלושת הקלטים קיימים. ממשיך לניתוח.

---

## [2] דשבורד תיק נוכחי

```
═══════════════════════════════════════
תמונת מצב תיק נוכחית
נקרא מהנתונים שסופקו — 27/05/2026
═══════════════════════════════════════

סה"כ שווי תיק:    $1,958.14
מזומן זמין:        $71.00  (3.6%)
מספר פוזיציות:    11
```

**הקצאת שכבות:**

| שכבה | קיים % | יעד % | סטטוס | פעולה נדרשת |
|---|---|---|---|---|
| Stability | 30.5% | 25-35% | 🟢 תקין | אין |
| Growth | 49.0% | 55-65% | 🔴 נמוך ב-6-16% | הוספה נדרשת |
| Speculation | 16.9% | 5-10% | 🔴 גבוה פי ~2 | קיצוץ דחוף |
| Cash | 3.6% | 5-10% | 🔴 נמוך | הגדלה נדרשת |

**פוזיציות מובילות:**

| # | שם | % תיק | שכבה | בעיה |
|---|---|---|---|---|
| 1 | NVDA | 13.7% | Growth | ⚠️ חורג ממגבלת 12% |
| 2 | IBIT | 10.5% | Speculation | 🔴 חורג ממגבלת 4% ספקולציה |
| 3 | META | 10.3% | Growth | 🟢 תקין |
| 4 | GOOG | 10.3% | Stability | 🟢 תקין |
| 5 | MSFT | 10.2% | Stability | 🟢 תקין |

**ריכוז לפי תמה:**

| תמה | % תיק |
|---|---|
| AI/Tech ליבה (NVDA+META+GOOG+MSFT+AVGO+MU) | 61.1% |
| AI תשתית/חשמל (VST) | 8.4% |
| ספקולציה (IBIT+OKLO+APLD) | 16.9% |
| זהב (GLDM) | 10.0% |
| מזומן | 3.6% |
| **AI/Tech כולל (כולל VST)** | **~69.5%** |

**נדרש איזון מחדש: כן**
→ Speculation 16.9% חורגת מהיעד 5-10% ב-6.9 עד 11.9 נקודות אחוז.
→ IBIT (10.5%) חורגת ממגבלת 4% לספקולציה ב-6.5%.
→ NVDA (13.7%) חורגת ממגבלת 12% לפוזיציה בודדת.
→ Cash (3.6%) מתחת לרצפת היעד 5%.

---

## [3] בדיקת התאמה לתיק

**שיוך שכבה:** Growth

**האם שכבת Growth פנויה?**
שכבת Growth עומדת על 49.0% לעומת יעד 55-65%. הכנסת AMZN ב-2.5% תביא ל-51.5%. עדיין מתחת לרצפת היעד. מהיבט שכבות בלבד: AMZN אינו מחריף. אבל שכבות הן לא המשתנה המגביל.

**ניתוח חפיפה:**

| פוזיציה | חפיפה | מנגנון | חומרה |
|---|---|---|---|
| NVDA (13.7%) | 🔴 ישירה | Amazon קונה GPU מ-NVIDIA, Trainium = ניסיון ביטול תלות | גבוהה |
| META (10.3%) | 🔴 ישירה | שני AI infra spenders, נפגעים יחד מירידת AI sentiment | גבוהה |
| GOOG (10.3%) | 🔴 ישירה | GCP = מתחרה ישיר ל-AWS | גבוהה |
| MSFT (10.2%) | 🔴 ישירה | Azure = מתחרה ישיר ל-AWS, גדל מהר יותר | גבוהה |
| MU (8.8%) | 🟡 עקיפה | Jassy: "memory costs skyrocketed" = Amazon לקוח של MU | בינונית |
| AVGO (7.8%) | 🟡 עקיפה | AI networking, אותו cycle השקעות | בינונית |
| VST (8.4%) | 🟡 עקיפה | ספקת חשמל ל-data centers, Amazon לקוח גדול | בינונית |

**4 פוזיציות בחפיפה ישירה.** הכלל: 3+ דורש הצדקה יוצאת דופן.

AMZN ב-2.5% יביא AI/Tech מ-69.5% ל-72%. זו לא הוספת גיוון, זו הגברת חשיפה לאותה תמה ב-7 כלים.

---

## [4] שווי והקצאת הון

**עלות הזדמנות: 3 חלופות:**

| חלופה | פוטנציאל | סיכון | R/R | פסיקה |
|---|---|---|---|---|
| 1. AMZN ב-$265.29 (עכשיו) | +3.8% לFV $275 (שורי-בסיס) | -22.7% לממוצע סקטור | 0.17:1 | ❌ לא עובר |
| 2. מזומן (4.3-4.5% risk-free) | 4.3-4.5% שנתי, ודאי | כמעט אפס | ∞ | ✅ עדיף כרגע |
| 3. AMZN ב-$230 (trigger) | +28% לFV $295 (IC estimate) | -18.7% ל-stop $187 | 1.49:1 | ✅ עובר בסיס |

**הערה על חלופה 4:** NOW (ServiceNow) נמצאת ב-$99.92 כרגע, 0.1% מתחת לטריגר $100. זהו APPROVED item עם R/R 2.2:1 לפי המחקר הקודם. תחרות ישירה על אותו הון.

**מסקנה:** ב-$265.29 אין alpha. ב-$230 יש alpha. המתנה היא לא פסיביות, היא עדיפה אקטיבית.

---

## [5] ביקורת סיכון התנהגותי

| הטיה | זוהה? | עוצמה | ראיה |
|---|---|---|---|
| FOMO | כן | 🟡 בינונית | AMZN עלתה 32% ב-52 שבועות, narrative חזק |
| Revenge Trade | לא | 🟢 נמוכה | אין הפסד קודם על AMZN |
| Overconfidence | כן | 🟡 בינונית | backlog $464B "מבטיח" מרגיש ודאי אך אינו |
| Narrative Bias | כן | 🔴 גבוהה | "AWS+Trainium+backlog" = סיפור שמרגש יותר מהמספרים |

**שאלות חובה:**

**למה עכשיו דווקא?**
AMZN על WATCHLIST עם trigger $230 מאז 26/05. המחיר כרגע $265.29, כלומר 15.3% מעל הטריגר. לא קרה שום דבר עסקי מהותי ב-24 שעות האחרונות. אין נימוק לכניסה.

**האם ההחלטה הייתה אותה הדבר אם המניה לא זזה השבוע?**
כן, כי ה-IC אמרה WATCHLIST כשהמניה הייתה $267.99 (אתמול). היום $265.29. המניה ירדה $2.70. אין שינוי עסקי.

**האם אני יכול להסביר את התזה בלי לצטט אחרים?**
כן: "AWS ו-Ads יצמחו 22-28%+ כי backlog $464B מבסס ביקוש, CapEx $300B ב-2025-2026 ייצר FCF recovery כמו logistics buildout 2023." ניתן להסביר. אבל timing ה-recovery אינו ודאי.

**מה יגרום לי להודות שטעיתי?**
AWS <22% YoY לשני רבעונים, FCF TTM <-$15B, FTC liability ruling.

**מפסק זרם:** לא הופעל. Narrative Bias גבוהה אך לא מגיעה לסף.

---

## [6] מנוע גודל פוזיציה

| פרמטר | ערך |
|---|---|
| שכנוע עסקי | גבוה (9/10 איכות) |
| סיכון כולל | גבוה (FCF שלילי, Azure threat, FTC 2027) |
| התאמה לתיק | נמוכה (AI concentration קיצוני) |

כלל: שכנוע גבוה + סיכון גבוה = הפחתה 30-60% ממקסימום.

| מגבלה | ערך |
|---|---|
| מקסימום שכבת Growth | 12% |
| מגבלת עורך הדין השטן | 4% (ציון 7/10) |
| IC approval | 2.5% (מותנה ב-trigger) |
| **CEO: גודל מאושר** | **0% עכשיו. 2.5% ב-$230 בלבד** |

---

## [7] המלצת איזון מחדש: נדרש בדחיפות

**IBIT הוא הבעיה הגדולה ביותר בתיק, לא AMZN.**

| שלב | פעולה | מה מוכרים | כמה | להיכן |
|---|---|---|---|---|
| 1 | מכור IBIT | 10.5% → 4% | ~$127.3 | Cash |
| 2 | מכור NVDA | 13.7% → 12% | ~$33.3 | Cash |
| 3 | Cash חדש | | ~$231.6 (~11.8%) | ביניים |
| 4 | AMZN (כש-$230) | | ~$49 (2.5%) | Growth |
| 5 | NOW (כש-$100) | | ~$49 (2.5%) | Growth |

לאחר ביצוע שלבים 1-5:
Cash: ~9.3% (בתוך יעד)
Speculation: ~10.4% (קרוב לגבול עליון)
Growth: ~54% (קרוב לרצפת היעד)

**שלב 1 ו-2 מיידיים, ללא תלות ב-AMZN.**

---

## ① פסיקת CEO: WATCHLIST (נשמר ללא שינוי)

## ② ציון התאמה לתיק: 4/10

| רכיב | ציון | הסבר |
|---|---|---|
| איכות עסק | 9/10 | אחת הפלטפורמות הטובות בהיסטוריה |
| שווי | 3/10 | EV $260.9 מתחת למחיר $265.29 |
| עיתוי | 2/10 | 15.3% מעל trigger, תנאים לא מולאו |
| התאמה לתיק | 3/10 | ריכוז AI 69.5%, speculation overweight |
| **ממוצע** | **4.25/10** | **לא עובר את הבר** |

## ③ שיוך שכבה: Growth

## ④ המלצת גודל פוזיציה: 0% עכשיו, 2.5% ב-$230

2.5% × $1,958 = $48.95 (לאחר rebalancing).
מוצלב: מגבלת שטן 4% ✓, מגבלת IC 2.5% ✓, מגבלת Growth 12% ✓.
**עכשיו: 0%.** R/R שלילי ללא מרווח ביטחון.

## ⑤ סיכון ריכוז: קריטי

ריכוז AI/Tech נוכחי: 69.5%.
עם AMZN 2.5%: 72.0%.
בבהלת AI correction של -40%: הפסד ~-29% על התיק הכולל.
זו לא הוספת פוזיציה, זה leverage על תמה קיימת.

## ⑥ החלטת שווי: יקר (גבולי)

Fair value בסיס: $255. מחיר נוכחי: $265.29 (פרמיה 4%).
EV expected value: $260.9 (מתחת למחיר).
Trigger $230: discount של 10% לFV, R/R מוצדק.
**פסיקה: הוגן-יקר ב-$265. אטרקטיבי ב-$230.**

## ⑦ עלות הזדמנות: מזומן עדיף עכשיו

1. AMZN ב-$265.29: R/R 0.17:1. לא עובר.
2. מזומן 4.3-4.5%: ריסק-פרי, מחכה להזדמנות.
3. AMZN ב-$230: R/R 1.49:1. עובר. (**4. NOW AT-TRIGGER: R/R 2.2:1 לפי ניתוח קיים.**)

## ⑧ ביקורת התנהגותית

| הטיה | זוהה? | עוצמה |
|---|---|---|
| FOMO | כן | 🟡 בינונית |
| Revenge Trade | לא | 🟢 נמוכה |
| Overconfidence | כן | 🟡 בינונית |
| Narrative Bias | כן | 🔴 גבוהה |

הטיה דומיננטית: **Narrative Bias.** AWS+Trainium+$464B backlog = נרטיב מרגש. אבל חישוב EV אומר משהו אחר.

## ⑨ מפסק זרם: לא הופעל

אין FOMO קריטי, אין revenge trade. Narrative Bias גבוהה אך מתחת לסף.

## ⑩ המלצת איזון מחדש: נדרש (ראה סעיף 7)

קצץ IBIT 6.5% + NVDA 1.7% → Cash. מיידי, ללא תלות ב-AMZN.

## ⑪ שלושה סיכוני תיק מובילים מהוספת AMZN

**1. AI Mega-Correction Amplification**
הוספת AMZN מביאה AI/Tech ל-72%+. NVDA+META+GOOG+MSFT+AVGO+MU+AMZN ירדו יחד בתרחיש AI correction. בירידה של -40%: הפסד של ~-29% על התיק. AMZN לא מגן, היא מגביר.

**2. FTC Binary Event בפוזיציה פתוחה**
כניסה עכשיו מעמידה חשיפה לפני FTC trial פברואר 2027. liability ruling: -25-40% ב-hours. עם 2.5%, נזק של -0.6 עד -1.0% לתיק. אבל הסיכון לא מפוצה ב-premium מספיק.

**3. Kill Switch Trajectory**
ה-kill switch (FCF TTM <$10B ב-Q4-2026) לא הופעל רשמית כי הבדיקה ב-Q4-2026. אבל FCF TTM כרגע -$2.47B עם CapEx annualizing ל-$173B. הוא לא מתקרב ל-$10B, הוא מתרחק. כניסה לפוזיציה כשה-kill switch בדרך לפריצה היא השקעה נגד הכלל שקבענו.

## ⑫ הסיבה החזקה ביותר לא לבצע

**Expected Value ($260.9) מתחת למחיר הנוכחי ($265.29).** לא נרטיב, לא תחושה. זה החישוב המתמטי של עורך הדין השטן עצמו, עם הסתברויות שהוא נתן. כשאין alpha, אין בסיס לכניסה.

## ⑬ האמת הקשה

התיק כבר "קנוי" על עלייה של AI דרך GOOG, MSFT, NVDA, MU, AVGO ו-VST. אם AWS ו-Trainium יצלחו, התיק ירוויח ממנו ישירות דרך 7 ערוצים קיימים. AMZN לא מוסיף חשיפה שאין לה, הוא מגביר חשיפה שיש לה יותר מדי. **הסיפור הנרגש מסתיר עובדה אחת: הגיוון בתיק הוא אשליה. כמעט הכל זז יחד.**

## ⑭ ציון שכנוע סופי: 4/10

## ⑮ החלטה סופית: WATCHLIST (ללא שינוי)

פסיקת ה-IC מ-26/05/2026 נשמרת. לא קרה שום דבר מהותי שמצדיק שינוי.

**פעולה ספציפית הבאה:**
1. **מיידי:** קצץ IBIT מ-10.5% ל-4% ← פעולה 1, דחוף
2. **מיידי:** קצץ NVDA מ-13.7% ל-12% ← פעולה 2, תיקון מגבלה
3. **שקול:** NOW AT-TRIGGER ($99.92) ← APPROVED item, R/R 2.2:1
4. **30 יולי 2026:** בדוק Q2 2026: AWS YoY ≥25%? CapEx ≤$55B/Q?
5. **כש-AMZN ≤$230:** כנס 2.5% בשלושה טרנשים ($230/$215/$200)

**תנאים שישנו את ההחלטה:**
- AMZN ≤$230 + Q2 אישור: Convert to APPROVED (2.5%)
- AWS Q2 2026 <25% YoY: Downgrade to REJECTED
- FTC liability ruling: Downgrade to REJECTED
- CapEx Q2 >$55B: Reevaluate, probable downgrade

## ⑯ שאלות חובה לפני ביצוע

**מהי התזה במשפט אחד?**
"AWS ו-Ads צומחים 22-28%+, backlog $464B מבסס ביקוש מבני, ו-CapEx $300B ב-2025-2026 ייצר FCF explosion ב-FY2027-2028 בדומה ל-logistics buildout 2021-2023."

**מה מוכיח שטענו?**
FCF חיובי $30B+ ב-FY2027, AWS YoY ≥22% בכל רבעון, Trainium penetration ≥30% ב-AWS compute, backlog conversion rate עולה.

**האם היינו קונים עוד אחרי -25%?**
ב-$199 (EV/EBITDA ~14x, P/S ~2.9x): כן, מגדיל ל-4%. ב-$265: לא.

---

```dashboard-json
{
  "ticker": "AMZN",
  "date": "2026-05-27",
  "verdict": "WATCHLIST",
  "score": 4,
  "thesis": "AWS+Ads צומחים 22-28%, backlog $464B מבסס ביקוש מבני. CapEx $300B ב-2025-2026 ייצר FCF recovery בFY2027-2028 כמו logistics cycle 2023. FCF kill switch בדרך לפריצה, מחיר 15.3% מעל trigger.",
  "key_risks": [
    "FCF TTM -$2.47B, CapEx $173B annualized: kill switch Q4-2026 בדרך לפריצה",
    "Azure +33-35% מגדיל enterprise market share בפער מואץ מול AWS +28%",
    "FTC Antitrust Trial פברואר 2027: binary event, downside קיומי ל-Marketplace flywheel"
  ],
  "position_size_pct": 0,
  "valuation_summary": "fair value $255 base. EV expected value $260.9 מתחת למחיר $265.29. כניסה מוצדקת ב-$230 בלבד (R/R 1.49:1). אין alpha עכשיו.",
  "entry_exit_plan": "עכשיו: 0%. T1 $230 (40%) · T2 $215 (30%) · T3 $200 (30%) · stop $187 · TP1 $295 · TP2 $380. פעולה נדרשת מיידית: קצץ IBIT מ-10.5% ל-4%, קצץ NVDA מ-13.7% ל-12%.",
  "handoff_summary": "CEO מאשר WATCHLIST ללא שינוי. מחיר $265.29 הוא 15.3% מעל trigger $230. שלושת תנאי IC לא מולאו: מחיר, IBIT rebalancing, Q2 confirmation. Speculation layer 16.9% vs 5-10% target הוא הבעיה הדחופה ביותר בתיק. פעולה מיידית: קצץ IBIT (6.5%) + NVDA (1.7%) לCash. EV $260.9 מתחת למחיר נוכחי, אין alpha. Next review: Q2 2026 earnings 30 יולי. שים לב: NOW AT-TRIGGER ב-$99.92, APPROVED item עם R/R 2.2:1 הוא הזדמנות מיידית יותר אטרקטיבית מ-AMZN."
}
```
