# ועדת ההשקעות — AMZN
## 27 מאי 2026 | מחיר: $265.29 | שווי שוק: $2.85T

---

## [1] אימות קלטים

| | | | |
|---|---|---|---|
| **HANDOFF אנליסט** | ✅ מלא | ציון איכות: 7.3/10 | שווי הוגן: $158–$418 (בסיס $255) |
| **HANDOFF עורך דין שטן** | ✅ מלא | ציון סיכון: 7/10 | מגבלת פוזיציה: 4% |
| **HANDOFF CEO** | ✅ מלא | החלטה: WATCHLIST | גודל מאושר: 0% עכשיו, 2.5% ב-$230 |
| **HANDOFF מבצע** | ✅ מלא (חלקי) | פסיקה: PENDING נתוני ביצוע | R/R במחיר נוכחי: 0.17:1 |

כל ארבעת ה-HANDOFFS התקבלו. הוועדה ממשיכת לניתוח.

**הסתייגות:** המבצע עצר לצורך נתוני ביצוע טכניים (RSI, ATR, DMA, VIX). ציון איכות כניסה ומשטר שוק אינם ידועים. הוועדה תפעל על בסיס ה-R/R הנגזר מ-CEO (0.17:1 נוכחי, 1.49:1 ב-$230).

---

## [2] ניתוח קונסנזוס

נקודות קונסנזוס:

✓ **איכות עסק גבוהה** — כל הסוכנים מסכימים: Amazon היא פלטפורמה עסקית חריגה. AWS+Ads = מנועי רווח בעלי חפיר רחב, מרווחים עולים, lock-in מבני.

✓ **AWS accelerating** — +28% YoY Q1 2026, backlog $464B, Trainium momentum. כל הסוכנים מייחסים לזה משקל גבוה בצד החיובי.

✓ **FCF TTM שלילי הוא בעיה** — -$2.47B TTM, CapEx $43.2B/Q annualizing ל-$173B. אף סוכן לא ניסה להקטין זאת.

✓ **מחיר נוכחי $265.29 אינו כניסה** — כל הסוכנים מסכימים: EV $260.9 מתחת למחיר, R/R 0.17:1, אין alpha.

✓ **trigger $230 הוא נקודת הכניסה** — עמדה עקבית בכל הסוכנים.

✓ **Azure הוא איום גדל** — כולם ציינו. הבדל בדגש בלבד.

קונסנזוס חזק = ביטחון גבוה — **ואותו קונסנזוס הוא גם דגל לחשיבת-עדר. ראה [6].**

---

## [3] ניתוח חילוקי דעות

### קונפליקט א: מה עושים עם ה-kill switch שנפרץ?

| | |
|---|---|
| **עורך דין שטן:** | "Kill switch FCF נפרץ כבר עכשיו. -$2.47B vs $10B threshold. זו לא 'אזהרה', זו עובדה. CapEx $173B annualized אומר FCF שלילי עמוק עד Q3 2027." → **הפחת לאזהרה אדומה** |
| **CEO:** | "Kill switch פורמלי בדיקה Q4-2026. FCF כרגע נפרץ אך הקריטריון הוא TTM ב-Q4-2026 ספציפית. WATCHLIST נשמר." → **הגנתי, הולך לפי אות החוק** |
| **ראיה לשטן:** | CapEx annualizing ל-$173B vs OCF est. $148B = FCF -$25B בFY2026. המסלול אינו מתקרב ל-$10B, הוא מתרחק. |
| **ראיה ל-CEO:** | Amazon עשתה את זה ב-logistics buildout 2021-2022. FCF חזר ב-2023-2024. precedent קיים. |
| **פסיקת ועדה:** | **עורך הדין השטן צודק יותר בסיכון, CEO צודק יותר בנוהל.** הוועדה מאמצת: kill switch הוא ב-"Yellow-Red transition". לא Rejected עדיין, אבל כל הפחתה בחומרת המצב היא רציונליזציה. Q2 2026 הוא רבעון קריטי: אם FCF לא מתחיל להתאושש, הוועדה מפעילה Rejected. |

---

### קונפליקט ב: האם Azure threat הוא "caveat" או "structural break"?

| | |
|---|---|
| **אנליסט:** | "Azure threat הוא caveat — AWS מחזיק 31% market share, backlog חזק." |
| **עורך דין שטן:** | "Azure +33-35% vs AWS +28% — gap 5-7 נקודות במשך 3+ רבעונים. new enterprise wins עוברים ל-Microsoft. זו שחיקה מבנית." |
| **ראיה לאנליסט:** | backlog $464B, Fortune 100 lock-in, 98% top EC2 customers on Graviton. |
| **ראיה לשטן:** | Azure Copilot+Teams+Office = enterprise ecosystem advantage שAWS אינו יכול לשכפל. Gap מואץ ולא מואט. |
| **פסיקת ועדה:** | **עורך הדין השטן צודק.** כשהפער גדל ברצועה עקבית של 3+ רבעונים, זהו pattern, לא noise. backlog מייצג לקוחות קיימים. ה-funnel של לקוחות חדשים — שהוא מה שקובע market share ב-2028 — מוטה Azure. הסוכנים האחרים הפחיתו מהמשקל של ממצא זה. |

---

### קונפליקט ג: האם Trainium "30% better price/performance" הוא ממשי?

| | |
|---|---|
| **אנליסט ו-CEO:** | מקבלים את הטענה כנכונה, מבססים עליה חיסכון פוטנציאלי של $30B+/שנה. |
| **עורך דין שטן:** | "Management's Unverified Claim. אין אימות עצמאי. NVIDIA Blackwell מצמצמת את הפער עם כל דור." |
| **פסיקת ועדה:** | **שניהם חלקית צודקים, אבל עורך הדין השטן מעלה נקודה מהותית.** הטענה אינה מאומתת. ועדה מוסיפה: השאלה אינה האם Trainium טוב מ-GPU ב-2026. השאלה: האם הוא מספיק טוב ב-2027-2028 כשNVIDIA B200/GB300 יהיו זמינים? בתרחיש שבו Trainium נכשל לשמור על היתרון, $30B+ מה-"חיסכון" חוזרים לCapEx NVIDIA. |

---

## [4] בדיקת מידע חסר

| אי-ודאות | רמה | השפעה |
|---|---|---|
| Backlog conversion rate ($464B → revenue) | 🔴 גבוהה | הנחת התזה כולה |
| CapEx ROI timeline ספציפי | 🔴 גבוהה | מתי FCF מתאושש? 2027? 2028? |
| Trainium performance vs Blackwell (עצמאי) | 🔴 גבוהה | האם $30B חיסכון אפשרי? |
| DSO/inventory quality trends | 🟡 בינונית | יושרה חשבונאית |
| נתוני ביצוע טכניים (RSI/ATR/DMA/VIX) | 🟡 בינונית | עיגון כניסה |
| Q3 2025 margin dip explanation (רשמי) | 🟡 בינונית | Pattern vs fluke? |
| SBC FY2026 quarterly breakdown | 🟡 בינונית | דילול |

**מסקנה:** שלוש אי-ודאויות גבוהות, כולן נוגעות לאותה הנחת ליבה: האם $300B CapEx יחזיר תשואה בזמן סביר? **אי-ודאות גבוהה → פוזיציה קטנה יותר ודחייה עד trigger.**

---

## [5] בדיקת איכות החלטה

| שאלה | תשובה |
|---|---|
| האם ההחלטה מבוססת על ראיות? | חלקית. איכות העסק מגובה ראיות. FCF recovery timeline — לא מגובה. |
| האם יש דחיפות רגשית? | כן. ירידה קלה $2.70 ב-24 שעות הגיעה ל-IC. אין שינוי עסקי מהותי. |
| האם FOMO קיים? | כן. +32% ב-52 שבועות + נרטיב Trainium/backlog. |
| האם Narrative Bias גבוהה? | 🔴 כן. "AWS+$464B backlog+Trainium" = נרטיב משכנע שמרגיש ודאי יותר מהחישוב. |
| אם ההשקעה תיכשל, האם התהליך היה נכון? | כן — ב-$230 כי R/R מוצדק. לא — ב-$265.29 כי אין alpha. |

**שאלה מרכזית:** "אם AWS יואט ל-18% ב-Q4 2026 ו-FCF יהיה -$20B TTM, האם נחשיב את ההחלטה כנכונה אם קנינו ב-$265?"

**תשובה:** לא. ב-$265.29 אין buffer. ב-$230 יש.

---

## [6] בדיקת חשיבת-עדר ונקודה עיוורת משותפת

⚠️ **נקודה עיוורת משותפת זוהתה — משמעותית.**

**ההנחה שכולם נשענו עליה ואיש לא ערער עליה ברצינות:**

> "ה-logistics buildout של 2021-2022 הוא אנלוגיה תקפה ל-AI buildout הנוכחי. FCF חזר ב-2023 — כך גם יחזור הפעם."

**למה זה עשוי להיות שגוי:**

1. **הסקייל שונה לחלוטין:** logistics CapEx: $52B. AI CapEx: $131B FY2025, ~$173B FY2026. יחס 3.3:1. ה-FCF recovery timeline ארוך בהרבה, ואף אחד לא מיפה את הפער הזה לשנים.

2. **בllogistics buildout לא הייתה Azure:** ב-2021-2022, Walmart ו-Target היו המתחרים ה-retail. AWS לא נלחמה על market share enterprise בפער מואץ. הפעם Microsoft Copilot+Azure יוצרים lock-in שלא היה ב-logistics race.

3. **efficiency risk:** כל ארבעת הסוכנים הניחו שביקוש ל-cloud AI inference ימשיך לגדול בקצב מספיק למימוש ROI. אף אחד לא שקל ברצינות: **מה אם model efficiency improvements (LLaMA, Gemma, Claude 4.x ועוד) יצמצמו את compute footprint לפי inference call מהר יותר ממה שהביקוש גדל?** Amazon עצמה השקיעה ב-Anthropic — שמפתחת דגמים יעילים יותר. אם Claude 5 דורש 60% פחות compute מ-Claude 4, ביקוש ה-GPU ל-inference עשוי לצנוח בה בעת שה-CapEx בנוי לצמיחה.

4. **הרציונליזציה של kill switch:** כולם ציינו שה-FCF kill switch נפרץ, ואז כולם המשיכו ל-WATCHLIST. הקונסנזוס על "WATCHLIST" עצמו עשוי להיות הטיית עדר: "כולנו אמרנו WATCHLIST, אז בטח זה נכון." המבחן האמיתי: אם kill switch היה "FCF TTM < $0" (ולא $10B) — מה היה הציון?

**השפעה על ועדה:**
- הורדת רמת ביטחון דרגה אחת: **מ"בינוני-גבוה" ל"בינוני"**
- הפחתת גודל פוזיציה מאושר: **2.5% → 2.0%** (הוועדה מממשת סמכות הקטנה)
- הוספת תנאי ל-trigger: בנוסף למחיר $230, נדרש Q2 2026 AWS ≥25% לאישור.

---

## [7] בדיקת השפעה על תיק

**ירושה מה-CEO (לא בנייה מחדש — בדיקה בלבד):**

| שאלה | תשובה | הערה |
|---|---|---|
| האם AMZN מחזק בניית תיק? | ❌ לא | מוסיף ריכוז, לא גיוון |
| האם ריכוז AI גדל? | כן: 69.5% → 72% | Threshold בעייתי |
| האם פיזור משתפר? | ❌ לא | 4 פוזיציות בחפיפה ישירה |
| האם הגודל המוצע מתאים? | כן (2.5%) | מתחת לכל תקרה |
| האם מזומן $71 (3.6%) טוב יותר? | כן — ב-$265.29 | 4.3-4.5% risk-free עדיף על EV $260.9 |

**ערך צפוי מותאם סיכון של הוספת AMZN ב-$265.29 ב-2.5%:**

| תרחיש | הסתברות | תשואה | תרומה לתיק |
|---|---|---|---|
| שורי (+55%) | 22% | +1.37% | +0.034% |
| בסיס (+5%) | 38% | +0.13% | +0.0049% |
| דובי (-32%) | 30% | -0.80% | -0.024% |
| אסון (-60%) | 10% | -1.50% | -0.015% |
| **EV מותאם** | | | **-0.00%** |

EV כמעט אפס ב-$265.29. **מוצדק רק ב-$230 כשה-EV עולה.**

---

## [8] פסיקת ועדה סופית

**WATCHLIST (מאושר פה אחד)**

ארבעת הסוכנים, כולל הוועדה — תמימי דעים. לא מקרה שמקווים בו; זה מבנה שדורש בסבלנות.

---

## טבלת קונסנזוס סוכנים

| נושא | אנליסט | שטן | CEO | מבצע | פסיקת ועדה |
|---|---|---|---|---|---|
| איכות עסק | ✅ 9/10 | ✅ גבוה | ✅ 9/10 | ✅ גבוה | **חזק** |
| רמת סיכון | 🟡 בינוני-גבוה | 🔴 7/10 גבוה | 🔴 גבוה | 🔴 FCF שלילי | **גבוה** |
| הערכת שווי | 🟡 הוגן-שולי | 🔴 EV מתחת למחיר | 🔴 גבולי יקר | ❌ חסר נתונים | **הוגן-יקר** |
| עיתוי כניסה | 🔴 לא (צריך $230) | 🔴 לא (EV<מחיר) | 🔴 לא (15% מעל trigger) | 🔴 R/R 0.17:1 | **גרוע** |
| גודל פוזיציה | 🟡 0%→2.5% | 🟡 מקס 4% | 🟡 0%→2.5% | 🟡 0% עכשיו | **0%→2.0% ב-$230** |
| המלצה סופית | 🟡 WATCHLIST | 🟡 WATCHLIST | 🟡 WATCHLIST | 🟡 PENDING | **WATCHLIST** |

---

## סיכום החלטה סופית

| מדד | ציון/הערכה |
|---|---|
| איכות עסק | **חזק** |
| סיכון | **גבוה** |
| שווי | **הוגן-יקר** |
| התאמה לתיק | **חלש** |
| איכות כניסה (נוכחית) | **גרועה** |
| נקודה עיוורת משותפת | **זוהתה** — אנלוגיית logistics + efficiency risk |
| ביטחון | **בינוני** (הורד דרגה) |
| גודל פוזיציה מומלץ | **0% עכשיו, 2.0% ב-$230** |
| החלטה סופית | **רשימת מעקב** |

---

---

# פלט נדרש — פסיקת ועדה

---

## ① פסיקת ועדה: WATCHLIST

---

## ② תמצית מנהלים

Amazon היא עסק חריג בעל חפיר רחב, אך המחיר הנוכחי $265.29 מגלם שווי הוגן ללא מרווח ביטחון — EV מחושב $260.9 נמוך ממחיר השוק. FCF TTM כבר שלילי (-$2.47B) עם CapEx $173B שנתי שלא מראה סימני האטה, בעוד Azure ממשיכה לגדול מהר יותר ב-5-7 נקודות אחוז בכל רבעון. הוועדה מאשרת WATCHLIST ללא שינוי: הכניסה מוצדקת רק ב-$230 עם אישור Q2 2026 AWS ≥25%. הפעולה הדחופה ביותר בתיק היא לא AMZN, אלא קיצוץ IBIT מ-10.5% ל-4%.

---

## ③ איכות עסק: חזק

AWS + Ads = שני מנועי רווח בעלי חפיר מבני, backlog $464B, מרווח תפעולי שיא 13.1%. אחת הפלטפורמות העסקיות הטובות ביותר בהיסטוריה. ציון אנליסט 9/10 מאושר.

---

## ④ הערכת סיכון: גבוה

שלושה סיכונים מובנים בו-זמנית: FCF שלילי ממושך, Azure market share capture מואצת, FTC binary event פברואר 2027. CapEx $173B annualized ללא IRR מוכח = ההימור הגדול ביותר שהחברה אי פעם לקחה.

---

## ⑤ הערכת שווי: הוגן-יקר

שווי הוגן בסיס: $255. מחיר נוכחי: $265.29 (פרמיה 4%). EV expected value $260.9 מתחת למחיר. FCF yield שלילי. P/E אמיתי (adjusted, ex-Anthropic): ~37x. ב-$230: discount לFV, R/R 1.49:1, מוצדק.

---

## ⑥ התאמה לתיק: חלש

ריכוז AI/Tech כבר 69.5% מהתיק. הוספת AMZN מביאה ל-72%. ארבע פוזיציות קיימות (GOOG, MSFT, NVDA, META) בחפיפה ישירה לAMZN. הוספת AMZN אינה גיוון — היא leverage על תמה קיימת. בתרחיש AI correction של -40%, התיק יורד -29%. זו הסיבה החזקה ביותר לא לכנוס ב-$265.

---

## ⑦ איכות כניסה: גרועה (נוכחית)

R/R במחיר נוכחי: 0.17:1. מחיר 15.3% מעל trigger $230. מבצע לא קיבל נתוני ביצוע טכניים (RSI/ATR/DMA חסרים). ב-$230: R/R 1.49:1 — עדיין מינימלי, אך עובר את סף 2:1 בתרחיש שורי. הוועדה מוסיפה תנאי: $230 + AWS Q2 ≥25% יחד.

---

## ⑧ קונסנזוס סוכנים

נקודות הסכמה חזקות:

✓ **AWS acceleration + backlog $464B** = ביקוש מבני אמיתי (כולם)
✓ **FCF TTM שלילי הוא סיכון מהותי** — לא ניתן להמעיט בו (כולם)
✓ **מחיר $265.29 אינו נקודת כניסה** — EV מתחת למחיר (כולם)
✓ **trigger $230 = כניסה מוצדקת** (כולם)
✓ **WATCHLIST ללא פעולה מיידית** (פה אחד)

---

## ⑨ חילוקי דעות מרכזיים

**חילוק א: Kill switch — רוח החוק מול אות החוק**

עורך דין שטן: "נפרץ עכשיו, דחה." CEO: "הבדיקה Q4-2026, WATCHLIST."
**פסיקת ועדה:** שניהם חלקית צודקים. הוועדה מגדירה: kill switch ב-"Yellow-Red". אם Q2 2026 FCF לא מראה שיפור מסלול, הוועדה עוברת ל-REJECTED ב-Q3.

**חילוק ב: Azure — caveat או structural break**

אנליסט: caveat בלבד. שטן: "structural capture of new enterprise."
**פסיקת ועדה:** עורך הדין השטן צודק. Gap 5-7 נקודות ב-3+ רבעונים הוא pattern. המשמעות: new enterprise wins הולכים ל-Azure. backlog $464B מגן על revenue הנוכחי אבל לא על הצמיחה העתידית.

**חילוק ג: Trainium ROI**

אנליסט ו-CEO: מניחים 30% better כנכון. שטן: לא מאומת.
**פסיקת ועדה:** השאלה הנכונה אינה 2026 אלא 2028. NVIDIA Blackwell ואחריו יצמצמו את הפער. הוועדה מפחית את ה-Trainium savings מ-$30B לנחישות לא ידועה עד ראיות עצמאיות.

---

## ⑩ איזה סוכן צפוי להיות הכי צודק?

**CEO — בשיפוט הכולל.**

הנימוק: CEO הוא הסוכן היחיד שחיבר בין EV expected value ($260.9), ריכוז תיק (69.5%), ועלות הזדמנות (NOW AT-TRIGGER ב-R/R 2.2:1) לכדי טיעון אחד עקבי. הוא לא התרגש מהנרטיב ולא מ-FCF panic, אלא אמר: "אין alpha עכשיו, יש alpha ב-$230, ויש הזדמנות טובה יותר זמינה."

**עורך הדין השטן — בסיכוי הספציפי.**

הנימוק: Azure threat severity מהנחה "caveat" ל-"structural" מבוסס על ראיה עקבית (3+ רבעונים של gap מואץ). גם ה-expected value calculation ($260.9) הוכיח נכונות מדויקת: EV מתחת למחיר = אין כניסה.

---

## ⑪ נקודה עיוורת משותפת

**זוהתה: אנלוגיית ה-logistics cycle.**

כל ארבעת הסוכנים נשענו על ההיסטוריה: "Amazon נכנסה ל-FCF שלילי ב-2021-2022 בגלל logistics buildout. FCF חזר ב-2023-2024. כך גם ה-AI buildout יעבוד."

**שלוש סיבות שהאנלוגיה עשויה להיות שבורה:**

1. **סקייל שונה:** logistics buildout = $52B CapEx. AI buildout = $131B+ → $173B+. כשהסקייל גדל פי 3.3, ה-recovery timeline ארוך בהרבה.

2. **תחרות שלא הייתה:** ב-2021-2022, AWS לא נלחמה על market share enterprise עם מתחרה שגדל 5-7 נקודות מהר יותר. הרגל logistics לא נגעה ב-AWS revenue. ה-AI buildout ופרסום Azure Copilot קורים בו-זמנית.

3. **efficiency risk:** Amazon משקיעה בAnthropic, שמפתחת דגמים יעילים יותר. אם inference efficiency משתפרת ב-40-60% לדור (מגמה קיימת), ביקוש ל-compute per query יורד. Amazon בנתה capacity לביקוש שעשוי לגדול איטי יותר ממה שציפתה.

**השפעה:** ביטחון הורד דרגה אחת. גודל פוזיציה הוקטן מ-2.5% ל-2.0%.

---

## ⑫ האי-ידוע הגדול ביותר שנותר

**Backlog conversion rate + ROI timeline.**

$464B backlog נשמע מרשים. אבל: מה שיעור ההמרה השנתי? מה ה-utilization rate הממוצע על נכסים שנפרסים? האם הלקוחות בbacklog מממשים את ההתחייבות בזמן, לפני הזמן, או מחכים? בלי נתון זה, כל תרחיש ROI הוא speculation. האנליסט ציין זאת. אף סוכן לא חקר.

**אם backlog conversion rate נמוך ב-30% מהצפוי:** FCF recovery נדחה שנה. $300B CapEx בלי revenue matching = FCF -$50B+ TTM עד 2027. תרחיש דובי הופך לתרחיש בסיס.

---

## ⑬ הטיעון החזק ביותר נגד השקעה

Amazon שורפת $173B שנתי על CapEx ומייצרת FCF שלילי, בעוד המתחרה הראשי (Azure) גדל מהר יותר ב-enterprise שמ — הדור הבא של לקוחות. כל ה-$300B CapEx מתבסס על הנחה שbacklog $464B יומר לrevenue בקצב ובמרווח שמצדיקים את ההשקעה — אבל conversion rate זה לא נמדד, לא מדווח, ולא אומת. כל הנרטיב השורי מבוסס על מדד שאינו קיים בדיווח הציבורי.

---

## ⑭ תנאים נדרשים לפני אישור

מכיוון שהפסיקה היא WATCHLIST, הוועדה מגדירה תנאים מדידים לConvert ל-APPROVED:

**תנאי 1 (מחיר):** AMZN ≤ $230.

**תנאי 2 (עסקי):** Q2 2026 AWS YoY ≥ 25% (confirmation שהacceleration ממשיך).

**תנאי 3 (FCF trajectory):** CapEx Q2 2026 ≤ $50B (כי $43.2B בQ1 → אין escalation).

**תנאי 4 (תיק):** IBIT הוקטן ל-4% לפני כניסה לAMZN (מזומן זמין לביצוע).

**אם רק תנאי 1 מולא אך לא 2+3:** כנס בטרנש מחצית בלבד ($230 × 40% = 1% מהתיק). המתן לאישור תנאים 2-3.

---

## ⑮ גודל פוזיציה מומלץ: 0% עכשיו → 2.0% ב-$230

**הפחתה מ-2.5% (CEO) ל-2.0% (ועדה):** בשל נקודה עיוורת משותפת שזוהתה + ביטחון שהורד דרגה.

**מגבלות:**
- מגבלת עורך דין שטן: 4% ✓
- מגבלת CEO מאושר: 2.5% ✓
- תקרת ועדה: 2.0% (הוקטן)

**פריסה ב-$230:** T1 $230 (50%) + T2 $215 (30%) + T3 $200 (20%). סה"כ: 2.0% מהתיק.

---

## ⑯ רמת ביטחון: בינוני

ירדה דרגה אחת מ"בינוני-גבוה" בשל נקודה עיוורת משותפת (אנלוגיית logistics), Azure threat severity מוחמרת, ו-backlog conversion rate לא ידוע.

---

## ⑰ האמת הקשה

**התיק כבר "קנוי" על הצלחת AWS דרך שבע פוזיציות קיימות.** GOOG, MSFT, NVDA, META, MU, AVGO, VST — כולן מרוויחות מהצלחת AWS ו-AI infrastructure. אם backlog $464B ימומש, Trainium יצליח, ו-AI capex יחזיר ROI — שבע הפוזיציות האלה יעלו. AMZN לא מוסיפה חשיפה שאין לה. הוא מגביר חשיפה שיש לה יתר על המידה. הגיוון בתיק הוא אשליה. כמעט הכל קורלטיבי. ולכן, גם אם AMZN היא עסק מדהים — זה לא המקום לה בתיק הזה ב-$265.

---

## ⑱ החלטת השקעה סופית: המתן / רשימת מעקב

AMZN היא עסק מצוין במחיר שאינו מציע alpha. EV $260.9 מתחת למחיר $265.29, R/R 0.17:1, FCF שלילי ומחריף, ריכוז AI בתיק 69.5%. כניסה נדרשת תנאים: (1) מחיר ≤$230, (2) Q2 AWS ≥25%, (3) CapEx Q2 ≤$50B, (4) IBIT הוקטן קודם.

**פעולה ספציפית הבאה:**
א. **מיידי:** קצץ IBIT מ-10.5% ל-4%. הפעולה הדחופה ביותר בתיק עכשיו.
ב. **מיידי:** קצץ NVDA מ-13.7% ל-12%.
ג. **שקול:** NOW AT-TRIGGER ($99.92) — APPROVED item עם R/R 2.2:1. עדיף על AMZN ב-$265.
ד. **30 יולי 2026:** בחן Q2 2026. אם תנאים 1-3 מולאו, Convert ל-APPROVED (2.0%).
ה. **AMZN ב-$230:** כנס T1 בתנאי תנאי 2-3 מאומתים.

---

## ⑲ לוח זמני מעקב (Watchlist — לא בוצעה עסקה)

| טריגר | סף | פעולה |
|---|---|---|
| **טריגר מחיר** | AMZN ≤ $230 | בדוק מחדש + אמת תנאים 2-3 |
| **טריגר זמן** | 30 יולי 2026 (Q2 earnings) | הרץ שרשרת מחדש אם נתונים השתנו |
| **טריגר עסקי חיובי** | AWS Q2 ≥25% YoY | שקול כניסה חלקית גם ב-$240-250 |
| **טריגר kill switch** | AWS YoY < 22% לשני רבעונים | הורד ל-REJECTED, הסר מ-watchlist |
| **טריגר kill switch** | FCF TTM < -$15B | הפחת לRejected |
| **טריגר בינארי** | FTC liability ruling | הסר מ-watchlist מיידית |
| **טריגר Azure** | Azure-AWS gap >+10 נקודות ל-3 רבעונים | reevaluate thesis |

**טריגר סקירה:** אם kill switch מופיע לפני 30 יולי — הערך מחדש מיידית, ללא המתנה לדוח.

---

```dashboard-json
{
  "ticker": "AMZN",
  "date": "2026-05-27",
  "verdict": "WATCHLIST",
  "score": 4,
  "thesis": "AWS+Ads צומחים 22-28% עם backlog $464B, אך FCF TTM שלילי (-$2.47B), CapEx $173B שנתי, Azure גדלה מהר יותר ב-enterprise, ו-EV $260.9 מתחת למחיר $265.29. כניסה מוצדקת רק ב-$230 עם אישור Q2.",
  "key_risks": [
    "FCF kill switch בדרך לפריצה: TTM -$2.47B עם CapEx $173B annualized, trajectory שלילי עד Q3 2027",
    "Azure enterprise capture: gap 5-7 נקודות לשלושה רבעונים רצופים — pattern מבני, לא noise",
    "FTC Antitrust Trial פברואר 2027: binary event עם downside קיומי ל-Marketplace flywheel"
  ],
  "position_size_pct": 0,
  "valuation_summary": "שווי הוגן בסיס $255, EV expected $260.9 מתחת למחיר $265.29. כניסה מוצדקת ב-$230 (R/R 1.49:1). גודל מאושר ועדה: 2.0% (הוקטן מ-2.5% בשל נקודה עיוורת שזוהתה).",
  "entry_exit_plan": "0% עכשיו. T1 $230 (50%) + T2 $215 (30%) + T3 $200 (20%) = 2.0% סה\"כ. תנאי כניסה: מחיר ≤$230 + Q2 AWS ≥25% + CapEx Q2 ≤$50B + IBIT הוקטן קודם. Stop ~$187. TP1 $295, TP2 $370.",
  "handoff_summary": "ועדת ההשקעות מאשרת WATCHLIST פה אחד — כל ארבעת הסוכנים עקביים. EV $260.9 מתחת למחיר $265.29, R/R 0.17:1, ריכוז AI בתיק 69.5%. נקודה עיוורת משותפת זוהתה: אנלוגיית logistics buildout 2021-2022 עשויה לא לחול על AI buildout פי 3.3 גדול יותר עם Azure תחרות מואצת. ביטחון הורד ל-בינוני, גודל הוקטן ל-2.0%. פעולה דחופה מיידית: קצץ IBIT 10.5%→4% וNVDA 13.7%→12% — אלה הדחופות ביותר, לא AMZN. Next review: Q2 2026 earnings 30 יולי 2026. כניסה תנאית: $230 + Q2 AWS ≥25% + CapEx Q2 ≤$50B."
}
```
